package entity;
// Generated Oct 11, 2015 7:56:58 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BigWinnersId generated by hbm2java
 */
@Embeddable
public class BigWinnersId  implements java.io.Serializable {


     private int bwId;
     private int tillTapeTId;
     private int tillTapeUsersUserId;
     private int tillTapeCustomersCustId;
     private int tillTapeLocationsLocId;

    public BigWinnersId() {
    }

    public BigWinnersId(int bwId, int tillTapeTId, int tillTapeUsersUserId, int tillTapeCustomersCustId, int tillTapeLocationsLocId) {
       this.bwId = bwId;
       this.tillTapeTId = tillTapeTId;
       this.tillTapeUsersUserId = tillTapeUsersUserId;
       this.tillTapeCustomersCustId = tillTapeCustomersCustId;
       this.tillTapeLocationsLocId = tillTapeLocationsLocId;
    }
   


    @Column(name="bw_id", unique=true, nullable=false)
    public int getBwId() {
        return this.bwId;
    }
    
    public void setBwId(int bwId) {
        this.bwId = bwId;
    }


    @Column(name="till_tape_t_id", nullable=false)
    public int getTillTapeTId() {
        return this.tillTapeTId;
    }
    
    public void setTillTapeTId(int tillTapeTId) {
        this.tillTapeTId = tillTapeTId;
    }


    @Column(name="till_tape_users_user_id", nullable=false)
    public int getTillTapeUsersUserId() {
        return this.tillTapeUsersUserId;
    }
    
    public void setTillTapeUsersUserId(int tillTapeUsersUserId) {
        this.tillTapeUsersUserId = tillTapeUsersUserId;
    }


    @Column(name="till_tape_customers_cust_id", nullable=false)
    public int getTillTapeCustomersCustId() {
        return this.tillTapeCustomersCustId;
    }
    
    public void setTillTapeCustomersCustId(int tillTapeCustomersCustId) {
        this.tillTapeCustomersCustId = tillTapeCustomersCustId;
    }


    @Column(name="till_tape_locations_loc_id", nullable=false)
    public int getTillTapeLocationsLocId() {
        return this.tillTapeLocationsLocId;
    }
    
    public void setTillTapeLocationsLocId(int tillTapeLocationsLocId) {
        this.tillTapeLocationsLocId = tillTapeLocationsLocId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BigWinnersId) ) return false;
		 BigWinnersId castOther = ( BigWinnersId ) other; 
         
		 return (this.getBwId()==castOther.getBwId())
 && (this.getTillTapeTId()==castOther.getTillTapeTId())
 && (this.getTillTapeUsersUserId()==castOther.getTillTapeUsersUserId())
 && (this.getTillTapeCustomersCustId()==castOther.getTillTapeCustomersCustId())
 && (this.getTillTapeLocationsLocId()==castOther.getTillTapeLocationsLocId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getBwId();
         result = 37 * result + this.getTillTapeTId();
         result = 37 * result + this.getTillTapeUsersUserId();
         result = 37 * result + this.getTillTapeCustomersCustId();
         result = 37 * result + this.getTillTapeLocationsLocId();
         return result;
   }   


}


