package entity;
// Generated Aug 1, 2015 5:45:51 PM by Hibernate Tools 4.3.1



/**
 * BigWinners generated by hbm2java
 */
public class BigWinners  implements java.io.Serializable {


     private BigWinnersId id;
     private TillTape tillTape;
     private Boolean w2g;

    public BigWinners() {
    }

	
    public BigWinners(BigWinnersId id, TillTape tillTape) {
        this.id = id;
        this.tillTape = tillTape;
    }
    public BigWinners(BigWinnersId id, TillTape tillTape, Boolean w2g) {
       this.id = id;
       this.tillTape = tillTape;
       this.w2g = w2g;
    }
   
    public BigWinnersId getId() {
        return this.id;
    }
    
    public void setId(BigWinnersId id) {
        this.id = id;
    }
    public TillTape getTillTape() {
        return this.tillTape;
    }
    
    public void setTillTape(TillTape tillTape) {
        this.tillTape = tillTape;
    }
    public Boolean getW2g() {
        return this.w2g;
    }
    
    public void setW2g(Boolean w2g) {
        this.w2g = w2g;
    }




}


