package entity;
// Generated Oct 8, 2015 11:06:13 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ClosedGames generated by hbm2java
 */
@Entity
@Table(name="closed games"
    ,catalog="fire_tickets"
)
public class ClosedGames  implements java.io.Serializable {


     private ClosedGamesId id;

    public ClosedGames() {
    }

    public ClosedGames(ClosedGamesId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="serial", column=@Column(name="Serial", nullable=false, length=12) ), 
        @AttributeOverride(name="datePlaced", column=@Column(name="Date_placed", length=10) ), 
        @AttributeOverride(name="dateRemoved", column=@Column(name="Date_removed", length=10) ), 
        @AttributeOverride(name="unsoldAmt", column=@Column(name="Unsold_amt") ), 
        @AttributeOverride(name="actualGross", column=@Column(name="Actual_gross") ), 
        @AttributeOverride(name="actualPrizes", column=@Column(name="Actual_prizes") ), 
        @AttributeOverride(name="actualNet", column=@Column(name="Actual_net") ), 
        @AttributeOverride(name="bin", column=@Column(name="Bin") ), 
        @AttributeOverride(name="inplay", column=@Column(name="Inplay") ), 
        @AttributeOverride(name="closed", column=@Column(name="Closed") ), 
        @AttributeOverride(name="unsoldTickets", column=@Column(name="Unsold_tickets") ), 
        @AttributeOverride(name="lastSaleRem", column=@Column(name="Last_sale_rem") ), 
        @AttributeOverride(name="prizeRem1", column=@Column(name="Prize_rem1") ), 
        @AttributeOverride(name="prizeRem2", column=@Column(name="Prize_rem2") ), 
        @AttributeOverride(name="prizeRem3", column=@Column(name="Prize_rem3") ), 
        @AttributeOverride(name="prizeRem4", column=@Column(name="Prize_rem4") ), 
        @AttributeOverride(name="prizeRem5", column=@Column(name="Prize_rem5") ), 
        @AttributeOverride(name="prizeRem6", column=@Column(name="Prize_rem6") ), 
        @AttributeOverride(name="prizeRem7", column=@Column(name="Prize_rem7") ), 
        @AttributeOverride(name="prizeRem8", column=@Column(name="Prize_rem8") ), 
        @AttributeOverride(name="prizeRem9", column=@Column(name="Prize_rem9") ), 
        @AttributeOverride(name="prizeRem10", column=@Column(name="Prize_rem10") ), 
        @AttributeOverride(name="prizeRem11", column=@Column(name="Prize_rem11") ), 
        @AttributeOverride(name="prizeRem12", column=@Column(name="Prize_rem12") ), 
        @AttributeOverride(name="prizeRem13", column=@Column(name="Prize_rem13") ), 
        @AttributeOverride(name="prizeRem14", column=@Column(name="Prize_rem14") ), 
        @AttributeOverride(name="prizeRem15", column=@Column(name="Prize_rem15") ), 
        @AttributeOverride(name="gameTemplatesPartNum", column=@Column(name="game_templates_part_num", nullable=false, length=12) ), 
        @AttributeOverride(name="datePurch", column=@Column(name="date_purch", length=10) ), 
        @AttributeOverride(name="invoiceNum", column=@Column(name="invoice_num", length=10) ), 
        @AttributeOverride(name="partNum", column=@Column(name="part_num", nullable=false, length=12) ), 
        @AttributeOverride(name="gameName", column=@Column(name="game_name", length=20) ), 
        @AttributeOverride(name="gameCost", column=@Column(name="game_cost", precision=22, scale=0) ), 
        @AttributeOverride(name="ticketCost", column=@Column(name="ticket_cost", precision=22, scale=0) ), 
        @AttributeOverride(name="numTickets", column=@Column(name="num_tickets") ), 
        @AttributeOverride(name="ideaGross", column=@Column(name="idea_gross") ), 
        @AttributeOverride(name="ideaPrizes", column=@Column(name="idea_prizes") ), 
        @AttributeOverride(name="ideaNet", column=@Column(name="idea_net") ), 
        @AttributeOverride(name="distsIdDistId", column=@Column(name="dists_id_dist_id", nullable=false) ), 
        @AttributeOverride(name="mfgIdMfgId", column=@Column(name="mfg_id_mfg_id", nullable=false) ), 
        @AttributeOverride(name="lastSale", column=@Column(name="Last_sale") ), 
        @AttributeOverride(name="lastSaleAllow", column=@Column(name="Last_sale_allow") ), 
        @AttributeOverride(name="prizeAmt1", column=@Column(name="Prize_amt1") ), 
        @AttributeOverride(name="prizeAmt2", column=@Column(name="Prize_amt2") ), 
        @AttributeOverride(name="prizeAmt3", column=@Column(name="Prize_amt3") ), 
        @AttributeOverride(name="prizeAmt4", column=@Column(name="Prize_amt4") ), 
        @AttributeOverride(name="prizeAmt5", column=@Column(name="Prize_amt5") ), 
        @AttributeOverride(name="prizeAmt6", column=@Column(name="Prize_amt6") ), 
        @AttributeOverride(name="prizeAmt7", column=@Column(name="Prize_amt7") ), 
        @AttributeOverride(name="prizeAmt8", column=@Column(name="Prize_amt8") ), 
        @AttributeOverride(name="prizeAmt9", column=@Column(name="Prize_amt9") ), 
        @AttributeOverride(name="prizeAmt10", column=@Column(name="Prize_amt10") ), 
        @AttributeOverride(name="prizeAmt11", column=@Column(name="Prize_amt11") ), 
        @AttributeOverride(name="prizeAmt12", column=@Column(name="Prize_amt12") ), 
        @AttributeOverride(name="prizeAmt13", column=@Column(name="Prize_amt13") ), 
        @AttributeOverride(name="prizeAmt14", column=@Column(name="Prize_amt14") ), 
        @AttributeOverride(name="prizeAmt15", column=@Column(name="Prize_amt15") ), 
        @AttributeOverride(name="prizeAll1", column=@Column(name="Prize_all1") ), 
        @AttributeOverride(name="prizeAll2", column=@Column(name="Prize_all2") ), 
        @AttributeOverride(name="prizeAll3", column=@Column(name="Prize_all3") ), 
        @AttributeOverride(name="prizeAll4", column=@Column(name="Prize_all4") ), 
        @AttributeOverride(name="prizeAll5", column=@Column(name="Prize_all5") ), 
        @AttributeOverride(name="prizeAll6", column=@Column(name="Prize_all6") ), 
        @AttributeOverride(name="prizeAll7", column=@Column(name="Prize_all7") ), 
        @AttributeOverride(name="prizeAll8", column=@Column(name="Prize_all8") ), 
        @AttributeOverride(name="prizeAll9", column=@Column(name="Prize_all9") ), 
        @AttributeOverride(name="prizeAll10", column=@Column(name="Prize_all10") ), 
        @AttributeOverride(name="prizeAll11", column=@Column(name="Prize_all11") ), 
        @AttributeOverride(name="prizeAll12", column=@Column(name="Prize_all12") ), 
        @AttributeOverride(name="prizeAll13", column=@Column(name="Prize_all13") ), 
        @AttributeOverride(name="prizeAll14", column=@Column(name="Prize_all14") ), 
        @AttributeOverride(name="prizeAll15", column=@Column(name="Prize_all15") ) } )
    public ClosedGamesId getId() {
        return this.id;
    }
    
    public void setId(ClosedGamesId id) {
        this.id = id;
    }




}


