package entity;
// Generated Aug 1, 2015 5:45:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customers generated by hbm2java
 */
public class Customers  implements java.io.Serializable {


     private Integer custId;
     private Integer cardNum;
     private String fname;
     private String lname;
     private String address;
     private String city;
     private String state;
     private String phone;
     private Integer totalSales;
     private Integer totalPrizes;
     private Set tillTapes = new HashSet(0);

    public Customers() {
    }

    public Customers(Integer cardNum, String fname, String lname, String address, String city, String state, String phone, Integer totalSales, Integer totalPrizes, Set tillTapes) {
       this.cardNum = cardNum;
       this.fname = fname;
       this.lname = lname;
       this.address = address;
       this.city = city;
       this.state = state;
       this.phone = phone;
       this.totalSales = totalSales;
       this.totalPrizes = totalPrizes;
       this.tillTapes = tillTapes;
    }
   
    public Integer getCustId() {
        return this.custId;
    }
    
    public void setCustId(Integer custId) {
        this.custId = custId;
    }
    public Integer getCardNum() {
        return this.cardNum;
    }
    
    public void setCardNum(Integer cardNum) {
        this.cardNum = cardNum;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Integer getTotalSales() {
        return this.totalSales;
    }
    
    public void setTotalSales(Integer totalSales) {
        this.totalSales = totalSales;
    }
    public Integer getTotalPrizes() {
        return this.totalPrizes;
    }
    
    public void setTotalPrizes(Integer totalPrizes) {
        this.totalPrizes = totalPrizes;
    }
    public Set getTillTapes() {
        return this.tillTapes;
    }
    
    public void setTillTapes(Set tillTapes) {
        this.tillTapes = tillTapes;
    }




}


