package entity;
// Generated Jul 18, 2015 10:35:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DistsId generated by hbm2java
 */
@Entity
@Table(name="dists_id"
    ,catalog="fire_tickets"
)
public class DistsId  implements java.io.Serializable {


     private Integer distId;
     private String distAbbr;
     private String name;
     private String address;
     private String city;
     private String state;
     private String licenseNum;
     private Set gameTemplateses = new HashSet(0);

    public DistsId() {
    }

    public DistsId(String distAbbr, String name, String address, String city, String state, String licenseNum, Set gameTemplateses) {
       this.distAbbr = distAbbr;
       this.name = name;
       this.address = address;
       this.city = city;
       this.state = state;
       this.licenseNum = licenseNum;
       this.gameTemplateses = gameTemplateses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="dist_id", unique=true, nullable=false)
    public Integer getDistId() {
        return this.distId;
    }
    
    public void setDistId(Integer distId) {
        this.distId = distId;
    }

    
    @Column(name="dist_abbr", length=10)
    public String getDistAbbr() {
        return this.distAbbr;
    }
    
    public void setDistAbbr(String distAbbr) {
        this.distAbbr = distAbbr;
    }

    
    @Column(name="name", length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="address", length=30)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="city", length=30)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="state", length=30)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="license_num", length=12)
    public String getLicenseNum() {
        return this.licenseNum;
    }
    
    public void setLicenseNum(String licenseNum) {
        this.licenseNum = licenseNum;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="distsId")
    public Set getGameTemplateses() {
        return this.gameTemplateses;
    }
    
    public void setGameTemplateses(Set gameTemplateses) {
        this.gameTemplateses = gameTemplateses;
    }




}


