package entity;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DistsId generated by hbm2java
 */
public class DistsId  implements java.io.Serializable {


     private Integer distId;
     private String distAbbr;
     private String name;
     private String address;
     private String city;
     private String state;
     private String licenseNum;
     private Set gameTemplateses = new HashSet(0);

    public DistsId() {
    }

    public DistsId(String distAbbr, String name, String address, String city, String state, String licenseNum, Set gameTemplateses) {
       this.distAbbr = distAbbr;
       this.name = name;
       this.address = address;
       this.city = city;
       this.state = state;
       this.licenseNum = licenseNum;
       this.gameTemplateses = gameTemplateses;
    }
   
    public Integer getDistId() {
        return this.distId;
    }
    
    public void setDistId(Integer distId) {
        this.distId = distId;
    }
    public String getDistAbbr() {
        return this.distAbbr;
    }
    
    public void setDistAbbr(String distAbbr) {
        this.distAbbr = distAbbr;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getLicenseNum() {
        return this.licenseNum;
    }
    
    public void setLicenseNum(String licenseNum) {
        this.licenseNum = licenseNum;
    }
    public Set getGameTemplateses() {
        return this.gameTemplateses;
    }
    
    public void setGameTemplateses(Set gameTemplateses) {
        this.gameTemplateses = gameTemplateses;
    }

    @Override
    public String toString() {
        return "DistsId{" + "distId=" + distId + ", distAbbr=" + distAbbr + ", name=" + name + ", address=" + address + ", city=" + city + ", state=" + state + ", licenseNum=" + licenseNum + ", gameTemplateses=" + gameTemplateses + '}';
    }




}


