package entity;
// Generated Aug 1, 2015 5:45:51 PM by Hibernate Tools 4.3.1



/**
 * GameTemplatesId generated by hbm2java
 */
public class GameTemplatesId  implements java.io.Serializable {


     private String partNum;
     private int distsIdDistId;
     private int mfgIdMfgId;

    public GameTemplatesId() {
    }

    public GameTemplatesId(String partNum, int distsIdDistId, int mfgIdMfgId) {
       this.partNum = partNum;
       this.distsIdDistId = distsIdDistId;
       this.mfgIdMfgId = mfgIdMfgId;
    }
   
    public String getPartNum() {
        return this.partNum;
    }
    
    public void setPartNum(String partNum) {
        this.partNum = partNum;
    }
    public int getDistsIdDistId() {
        return this.distsIdDistId;
    }
    
    public void setDistsIdDistId(int distsIdDistId) {
        this.distsIdDistId = distsIdDistId;
    }
    public int getMfgIdMfgId() {
        return this.mfgIdMfgId;
    }
    
    public void setMfgIdMfgId(int mfgIdMfgId) {
        this.mfgIdMfgId = mfgIdMfgId;
    }




}


