package entity;
// Generated Jul 18, 2015 9:05:31 PM by Hibernate Tools 4.3.1



/**
 * Game_Templates generated by hbm2java
 */
public class Game_Templates  implements java.io.Serializable {


     private String partNum;
     private int distID;
     private double gameCost;
     private String gameName;
     private int idealGross;
     private int idealNet;
     private int idealPrizes;
     private String invoiceNum;
     private double lastSale;
     private int lastSaleAllowed;
     private int mfgID;
     private int numTickets;
     private double prizeAllowed;
     private double prizeAmount;
     private double ticketCost;

    public Game_Templates() {
    }

	
    public Game_Templates(String partNum, int distID, double gameCost, int idealGross, int idealNet, int idealPrizes, double lastSale, int lastSaleAllowed, int mfgID, int numTickets, double prizeAllowed, double prizeAmount, double ticketCost) {
        this.partNum = partNum;
        this.distID = distID;
        this.gameCost = gameCost;
        this.idealGross = idealGross;
        this.idealNet = idealNet;
        this.idealPrizes = idealPrizes;
        this.lastSale = lastSale;
        this.lastSaleAllowed = lastSaleAllowed;
        this.mfgID = mfgID;
        this.numTickets = numTickets;
        this.prizeAllowed = prizeAllowed;
        this.prizeAmount = prizeAmount;
        this.ticketCost = ticketCost;
    }
    public Game_Templates(String partNum, int distID, double gameCost, String gameName, int idealGross, int idealNet, int idealPrizes, String invoiceNum, double lastSale, int lastSaleAllowed, int mfgID, int numTickets, double prizeAllowed, double prizeAmount, double ticketCost) {
       this.partNum = partNum;
       this.distID = distID;
       this.gameCost = gameCost;
       this.gameName = gameName;
       this.idealGross = idealGross;
       this.idealNet = idealNet;
       this.idealPrizes = idealPrizes;
       this.invoiceNum = invoiceNum;
       this.lastSale = lastSale;
       this.lastSaleAllowed = lastSaleAllowed;
       this.mfgID = mfgID;
       this.numTickets = numTickets;
       this.prizeAllowed = prizeAllowed;
       this.prizeAmount = prizeAmount;
       this.ticketCost = ticketCost;
    }
   
    public String getPartNum() {
        return this.partNum;
    }
    
    public void setPartNum(String partNum) {
        this.partNum = partNum;
    }
    public int getDistID() {
        return this.distID;
    }
    
    public void setDistID(int distID) {
        this.distID = distID;
    }
    public double getGameCost() {
        return this.gameCost;
    }
    
    public void setGameCost(double gameCost) {
        this.gameCost = gameCost;
    }
    public String getGameName() {
        return this.gameName;
    }
    
    public void setGameName(String gameName) {
        this.gameName = gameName;
    }
    public int getIdealGross() {
        return this.idealGross;
    }
    
    public void setIdealGross(int idealGross) {
        this.idealGross = idealGross;
    }
    public int getIdealNet() {
        return this.idealNet;
    }
    
    public void setIdealNet(int idealNet) {
        this.idealNet = idealNet;
    }
    public int getIdealPrizes() {
        return this.idealPrizes;
    }
    
    public void setIdealPrizes(int idealPrizes) {
        this.idealPrizes = idealPrizes;
    }
    public String getInvoiceNum() {
        return this.invoiceNum;
    }
    
    public void setInvoiceNum(String invoiceNum) {
        this.invoiceNum = invoiceNum;
    }
    public double getLastSale() {
        return this.lastSale;
    }
    
    public void setLastSale(double lastSale) {
        this.lastSale = lastSale;
    }
    public int getLastSaleAllowed() {
        return this.lastSaleAllowed;
    }
    
    public void setLastSaleAllowed(int lastSaleAllowed) {
        this.lastSaleAllowed = lastSaleAllowed;
    }
    public int getMfgID() {
        return this.mfgID;
    }
    
    public void setMfgID(int mfgID) {
        this.mfgID = mfgID;
    }
    public int getNumTickets() {
        return this.numTickets;
    }
    
    public void setNumTickets(int numTickets) {
        this.numTickets = numTickets;
    }
    public double getPrizeAllowed() {
        return this.prizeAllowed;
    }
    
    public void setPrizeAllowed(double prizeAllowed) {
        this.prizeAllowed = prizeAllowed;
    }
    public double getPrizeAmount() {
        return this.prizeAmount;
    }
    
    public void setPrizeAmount(double prizeAmount) {
        this.prizeAmount = prizeAmount;
    }
    public double getTicketCost() {
        return this.ticketCost;
    }
    
    public void setTicketCost(double ticketCost) {
        this.ticketCost = ticketCost;
    }




}


