package entity;
// Generated Aug 1, 2015 5:45:51 PM by Hibernate Tools 4.3.1



/**
 * InplayGames generated by hbm2java
 */
public class InplayGames  implements java.io.Serializable {


     private InplayGamesId id;

    public InplayGames() {
    }

    public InplayGames(InplayGamesId id) {
       this.id = id;
    }
   
    public InplayGamesId getId() {
        return this.id;
    }
    
    public void setId(InplayGamesId id) {
        this.id = id;
    }




}


