package entity;
// Generated Oct 11, 2015 7:56:58 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InplayGames generated by hbm2java
 */
@Entity
@Table(name="inplay_games"
    ,catalog="fire_tickets"
)
public class InplayGames  implements java.io.Serializable {


     private InplayGamesId id;

    public InplayGames() {
    }

    public InplayGames(InplayGamesId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="serial", column=@Column(name="Serial", nullable=false, length=12) ), 
        @AttributeOverride(name="datePlaced", column=@Column(name="Date_placed", length=10) ), 
        @AttributeOverride(name="dateRemoved", column=@Column(name="Date_removed", length=10) ), 
        @AttributeOverride(name="unsoldAmt", column=@Column(name="Unsold_amt") ), 
        @AttributeOverride(name="actualGross", column=@Column(name="Actual_gross") ), 
        @AttributeOverride(name="actualPrizes", column=@Column(name="Actual_prizes") ), 
        @AttributeOverride(name="actualNet", column=@Column(name="Actual_net") ), 
        @AttributeOverride(name="bin", column=@Column(name="Bin") ), 
        @AttributeOverride(name="inplay", column=@Column(name="Inplay") ), 
        @AttributeOverride(name="closed", column=@Column(name="Closed") ), 
        @AttributeOverride(name="unsoldTickets", column=@Column(name="Unsold_tickets") ), 
        @AttributeOverride(name="lastSaleRem", column=@Column(name="Last_sale_rem") ), 
        @AttributeOverride(name="prizeRem1", column=@Column(name="Prize_rem1") ), 
        @AttributeOverride(name="prizeRem2", column=@Column(name="Prize_rem2") ), 
        @AttributeOverride(name="prizeRem3", column=@Column(name="Prize_rem3") ), 
        @AttributeOverride(name="prizeRem4", column=@Column(name="Prize_rem4") ), 
        @AttributeOverride(name="prizeRem5", column=@Column(name="Prize_rem5") ), 
        @AttributeOverride(name="prizeRem6", column=@Column(name="Prize_rem6") ), 
        @AttributeOverride(name="prizeRem7", column=@Column(name="Prize_rem7") ), 
        @AttributeOverride(name="prizeRem8", column=@Column(name="Prize_rem8") ), 
        @AttributeOverride(name="prizeRem9", column=@Column(name="Prize_rem9") ), 
        @AttributeOverride(name="prizeRem10", column=@Column(name="Prize_rem10") ), 
        @AttributeOverride(name="prizeRem11", column=@Column(name="Prize_rem11") ), 
        @AttributeOverride(name="prizeRem12", column=@Column(name="Prize_rem12") ), 
        @AttributeOverride(name="prizeRem13", column=@Column(name="Prize_rem13") ), 
        @AttributeOverride(name="prizeRem14", column=@Column(name="Prize_rem14") ), 
        @AttributeOverride(name="prizeRem15", column=@Column(name="Prize_rem15") ), 
        @AttributeOverride(name="gameTemplatesPartNum", column=@Column(name="game_templates_part_num", nullable=false, length=12) ), 
        @AttributeOverride(name="datePurch", column=@Column(name="date_purch", length=10) ), 
        @AttributeOverride(name="invoiceNum", column=@Column(name="invoice_num", length=10) ) } )
    public InplayGamesId getId() {
        return this.id;
    }
    
    public void setId(InplayGamesId id) {
        this.id = id;
    }




}


