package entity;
// Generated Oct 8, 2015 11:06:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InventoryId generated by hbm2java
 */
@Embeddable
public class InventoryId  implements java.io.Serializable {


     private String serial;
     private Date datePlaced;
     private Date dateRemoved;
     private Integer unsoldAmt;
     private Integer actualGross;
     private Integer actualPrizes;
     private Integer actualNet;
     private Integer bin;
     private Boolean inplay;
     private Integer closed;
     private Integer unsoldTickets;
     private Byte lastSaleRem;
     private Integer prizeRem1;
     private Integer prizeRem2;
     private Integer prizeRem3;
     private Integer prizeRem4;
     private Integer prizeRem5;
     private Integer prizeRem6;
     private Integer prizeRem7;
     private Integer prizeRem8;
     private Integer prizeRem9;
     private Integer prizeRem10;
     private Integer prizeRem11;
     private Integer prizeRem12;
     private Integer prizeRem13;
     private Integer prizeRem14;
     private Integer prizeRem15;
     private String gameTemplatesPartNum;
     private Date datePurch;
     private String invoiceNum;
     private String partNum;
     private String gameName;
     private Double gameCost;
     private Double ticketCost;
     private Integer numTickets;
     private Integer ideaGross;
     private Integer ideaPrizes;
     private Integer ideaNet;
     private int distsIdDistId;
     private int mfgIdMfgId;
     private Integer lastSale;
     private Integer lastSaleAllow;
     private Integer prizeAmt1;
     private Integer prizeAmt2;
     private Integer prizeAmt3;
     private Integer prizeAmt4;
     private Integer prizeAmt5;
     private Integer prizeAmt6;
     private Integer prizeAmt7;
     private Integer prizeAmt8;
     private Integer prizeAmt9;
     private Integer prizeAmt10;
     private Integer prizeAmt11;
     private Integer prizeAmt12;
     private Integer prizeAmt13;
     private Integer prizeAmt14;
     private Integer prizeAmt15;
     private Integer prizeAll1;
     private Integer prizeAll2;
     private Integer prizeAll3;
     private Integer prizeAll4;
     private Integer prizeAll5;
     private Integer prizeAll6;
     private Integer prizeAll7;
     private Integer prizeAll8;
     private Integer prizeAll9;
     private Integer prizeAll10;
     private Integer prizeAll11;
     private Integer prizeAll12;
     private Integer prizeAll13;
     private Integer prizeAll14;
     private Integer prizeAll15;

    public InventoryId() {
    }

	
    public InventoryId(String serial, String gameTemplatesPartNum, String partNum, int distsIdDistId, int mfgIdMfgId) {
        this.serial = serial;
        this.gameTemplatesPartNum = gameTemplatesPartNum;
        this.partNum = partNum;
        this.distsIdDistId = distsIdDistId;
        this.mfgIdMfgId = mfgIdMfgId;
    }
    public InventoryId(String serial, Date datePlaced, Date dateRemoved, Integer unsoldAmt, Integer actualGross, Integer actualPrizes, Integer actualNet, Integer bin, Boolean inplay, Integer closed, Integer unsoldTickets, Byte lastSaleRem, Integer prizeRem1, Integer prizeRem2, Integer prizeRem3, Integer prizeRem4, Integer prizeRem5, Integer prizeRem6, Integer prizeRem7, Integer prizeRem8, Integer prizeRem9, Integer prizeRem10, Integer prizeRem11, Integer prizeRem12, Integer prizeRem13, Integer prizeRem14, Integer prizeRem15, String gameTemplatesPartNum, Date datePurch, String invoiceNum, String partNum, String gameName, Double gameCost, Double ticketCost, Integer numTickets, Integer ideaGross, Integer ideaPrizes, Integer ideaNet, int distsIdDistId, int mfgIdMfgId, Integer lastSale, Integer lastSaleAllow, Integer prizeAmt1, Integer prizeAmt2, Integer prizeAmt3, Integer prizeAmt4, Integer prizeAmt5, Integer prizeAmt6, Integer prizeAmt7, Integer prizeAmt8, Integer prizeAmt9, Integer prizeAmt10, Integer prizeAmt11, Integer prizeAmt12, Integer prizeAmt13, Integer prizeAmt14, Integer prizeAmt15, Integer prizeAll1, Integer prizeAll2, Integer prizeAll3, Integer prizeAll4, Integer prizeAll5, Integer prizeAll6, Integer prizeAll7, Integer prizeAll8, Integer prizeAll9, Integer prizeAll10, Integer prizeAll11, Integer prizeAll12, Integer prizeAll13, Integer prizeAll14, Integer prizeAll15) {
       this.serial = serial;
       this.datePlaced = datePlaced;
       this.dateRemoved = dateRemoved;
       this.unsoldAmt = unsoldAmt;
       this.actualGross = actualGross;
       this.actualPrizes = actualPrizes;
       this.actualNet = actualNet;
       this.bin = bin;
       this.inplay = inplay;
       this.closed = closed;
       this.unsoldTickets = unsoldTickets;
       this.lastSaleRem = lastSaleRem;
       this.prizeRem1 = prizeRem1;
       this.prizeRem2 = prizeRem2;
       this.prizeRem3 = prizeRem3;
       this.prizeRem4 = prizeRem4;
       this.prizeRem5 = prizeRem5;
       this.prizeRem6 = prizeRem6;
       this.prizeRem7 = prizeRem7;
       this.prizeRem8 = prizeRem8;
       this.prizeRem9 = prizeRem9;
       this.prizeRem10 = prizeRem10;
       this.prizeRem11 = prizeRem11;
       this.prizeRem12 = prizeRem12;
       this.prizeRem13 = prizeRem13;
       this.prizeRem14 = prizeRem14;
       this.prizeRem15 = prizeRem15;
       this.gameTemplatesPartNum = gameTemplatesPartNum;
       this.datePurch = datePurch;
       this.invoiceNum = invoiceNum;
       this.partNum = partNum;
       this.gameName = gameName;
       this.gameCost = gameCost;
       this.ticketCost = ticketCost;
       this.numTickets = numTickets;
       this.ideaGross = ideaGross;
       this.ideaPrizes = ideaPrizes;
       this.ideaNet = ideaNet;
       this.distsIdDistId = distsIdDistId;
       this.mfgIdMfgId = mfgIdMfgId;
       this.lastSale = lastSale;
       this.lastSaleAllow = lastSaleAllow;
       this.prizeAmt1 = prizeAmt1;
       this.prizeAmt2 = prizeAmt2;
       this.prizeAmt3 = prizeAmt3;
       this.prizeAmt4 = prizeAmt4;
       this.prizeAmt5 = prizeAmt5;
       this.prizeAmt6 = prizeAmt6;
       this.prizeAmt7 = prizeAmt7;
       this.prizeAmt8 = prizeAmt8;
       this.prizeAmt9 = prizeAmt9;
       this.prizeAmt10 = prizeAmt10;
       this.prizeAmt11 = prizeAmt11;
       this.prizeAmt12 = prizeAmt12;
       this.prizeAmt13 = prizeAmt13;
       this.prizeAmt14 = prizeAmt14;
       this.prizeAmt15 = prizeAmt15;
       this.prizeAll1 = prizeAll1;
       this.prizeAll2 = prizeAll2;
       this.prizeAll3 = prizeAll3;
       this.prizeAll4 = prizeAll4;
       this.prizeAll5 = prizeAll5;
       this.prizeAll6 = prizeAll6;
       this.prizeAll7 = prizeAll7;
       this.prizeAll8 = prizeAll8;
       this.prizeAll9 = prizeAll9;
       this.prizeAll10 = prizeAll10;
       this.prizeAll11 = prizeAll11;
       this.prizeAll12 = prizeAll12;
       this.prizeAll13 = prizeAll13;
       this.prizeAll14 = prizeAll14;
       this.prizeAll15 = prizeAll15;
    }
   


    @Column(name="Serial", nullable=false, length=12)
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }


    @Column(name="Date_placed", length=10)
    public Date getDatePlaced() {
        return this.datePlaced;
    }
    
    public void setDatePlaced(Date datePlaced) {
        this.datePlaced = datePlaced;
    }


    @Column(name="Date_removed", length=10)
    public Date getDateRemoved() {
        return this.dateRemoved;
    }
    
    public void setDateRemoved(Date dateRemoved) {
        this.dateRemoved = dateRemoved;
    }


    @Column(name="Unsold_amt")
    public Integer getUnsoldAmt() {
        return this.unsoldAmt;
    }
    
    public void setUnsoldAmt(Integer unsoldAmt) {
        this.unsoldAmt = unsoldAmt;
    }


    @Column(name="Actual_gross")
    public Integer getActualGross() {
        return this.actualGross;
    }
    
    public void setActualGross(Integer actualGross) {
        this.actualGross = actualGross;
    }


    @Column(name="Actual_prizes")
    public Integer getActualPrizes() {
        return this.actualPrizes;
    }
    
    public void setActualPrizes(Integer actualPrizes) {
        this.actualPrizes = actualPrizes;
    }


    @Column(name="Actual_net")
    public Integer getActualNet() {
        return this.actualNet;
    }
    
    public void setActualNet(Integer actualNet) {
        this.actualNet = actualNet;
    }


    @Column(name="Bin")
    public Integer getBin() {
        return this.bin;
    }
    
    public void setBin(Integer bin) {
        this.bin = bin;
    }


    @Column(name="Inplay")
    public Boolean getInplay() {
        return this.inplay;
    }
    
    public void setInplay(Boolean inplay) {
        this.inplay = inplay;
    }


    @Column(name="Closed")
    public Integer getClosed() {
        return this.closed;
    }
    
    public void setClosed(Integer closed) {
        this.closed = closed;
    }


    @Column(name="Unsold_tickets")
    public Integer getUnsoldTickets() {
        return this.unsoldTickets;
    }
    
    public void setUnsoldTickets(Integer unsoldTickets) {
        this.unsoldTickets = unsoldTickets;
    }


    @Column(name="Last_sale_rem")
    public Byte getLastSaleRem() {
        return this.lastSaleRem;
    }
    
    public void setLastSaleRem(Byte lastSaleRem) {
        this.lastSaleRem = lastSaleRem;
    }


    @Column(name="Prize_rem1")
    public Integer getPrizeRem1() {
        return this.prizeRem1;
    }
    
    public void setPrizeRem1(Integer prizeRem1) {
        this.prizeRem1 = prizeRem1;
    }


    @Column(name="Prize_rem2")
    public Integer getPrizeRem2() {
        return this.prizeRem2;
    }
    
    public void setPrizeRem2(Integer prizeRem2) {
        this.prizeRem2 = prizeRem2;
    }


    @Column(name="Prize_rem3")
    public Integer getPrizeRem3() {
        return this.prizeRem3;
    }
    
    public void setPrizeRem3(Integer prizeRem3) {
        this.prizeRem3 = prizeRem3;
    }


    @Column(name="Prize_rem4")
    public Integer getPrizeRem4() {
        return this.prizeRem4;
    }
    
    public void setPrizeRem4(Integer prizeRem4) {
        this.prizeRem4 = prizeRem4;
    }


    @Column(name="Prize_rem5")
    public Integer getPrizeRem5() {
        return this.prizeRem5;
    }
    
    public void setPrizeRem5(Integer prizeRem5) {
        this.prizeRem5 = prizeRem5;
    }


    @Column(name="Prize_rem6")
    public Integer getPrizeRem6() {
        return this.prizeRem6;
    }
    
    public void setPrizeRem6(Integer prizeRem6) {
        this.prizeRem6 = prizeRem6;
    }


    @Column(name="Prize_rem7")
    public Integer getPrizeRem7() {
        return this.prizeRem7;
    }
    
    public void setPrizeRem7(Integer prizeRem7) {
        this.prizeRem7 = prizeRem7;
    }


    @Column(name="Prize_rem8")
    public Integer getPrizeRem8() {
        return this.prizeRem8;
    }
    
    public void setPrizeRem8(Integer prizeRem8) {
        this.prizeRem8 = prizeRem8;
    }


    @Column(name="Prize_rem9")
    public Integer getPrizeRem9() {
        return this.prizeRem9;
    }
    
    public void setPrizeRem9(Integer prizeRem9) {
        this.prizeRem9 = prizeRem9;
    }


    @Column(name="Prize_rem10")
    public Integer getPrizeRem10() {
        return this.prizeRem10;
    }
    
    public void setPrizeRem10(Integer prizeRem10) {
        this.prizeRem10 = prizeRem10;
    }


    @Column(name="Prize_rem11")
    public Integer getPrizeRem11() {
        return this.prizeRem11;
    }
    
    public void setPrizeRem11(Integer prizeRem11) {
        this.prizeRem11 = prizeRem11;
    }


    @Column(name="Prize_rem12")
    public Integer getPrizeRem12() {
        return this.prizeRem12;
    }
    
    public void setPrizeRem12(Integer prizeRem12) {
        this.prizeRem12 = prizeRem12;
    }


    @Column(name="Prize_rem13")
    public Integer getPrizeRem13() {
        return this.prizeRem13;
    }
    
    public void setPrizeRem13(Integer prizeRem13) {
        this.prizeRem13 = prizeRem13;
    }


    @Column(name="Prize_rem14")
    public Integer getPrizeRem14() {
        return this.prizeRem14;
    }
    
    public void setPrizeRem14(Integer prizeRem14) {
        this.prizeRem14 = prizeRem14;
    }


    @Column(name="Prize_rem15")
    public Integer getPrizeRem15() {
        return this.prizeRem15;
    }
    
    public void setPrizeRem15(Integer prizeRem15) {
        this.prizeRem15 = prizeRem15;
    }


    @Column(name="game_templates_part_num", nullable=false, length=12)
    public String getGameTemplatesPartNum() {
        return this.gameTemplatesPartNum;
    }
    
    public void setGameTemplatesPartNum(String gameTemplatesPartNum) {
        this.gameTemplatesPartNum = gameTemplatesPartNum;
    }


    @Column(name="date_purch", length=10)
    public Date getDatePurch() {
        return this.datePurch;
    }
    
    public void setDatePurch(Date datePurch) {
        this.datePurch = datePurch;
    }


    @Column(name="invoice_num", length=10)
    public String getInvoiceNum() {
        return this.invoiceNum;
    }
    
    public void setInvoiceNum(String invoiceNum) {
        this.invoiceNum = invoiceNum;
    }


    @Column(name="part_num", nullable=false, length=12)
    public String getPartNum() {
        return this.partNum;
    }
    
    public void setPartNum(String partNum) {
        this.partNum = partNum;
    }


    @Column(name="game_name", length=20)
    public String getGameName() {
        return this.gameName;
    }
    
    public void setGameName(String gameName) {
        this.gameName = gameName;
    }


    @Column(name="game_cost", precision=22, scale=0)
    public Double getGameCost() {
        return this.gameCost;
    }
    
    public void setGameCost(Double gameCost) {
        this.gameCost = gameCost;
    }


    @Column(name="ticket_cost", precision=22, scale=0)
    public Double getTicketCost() {
        return this.ticketCost;
    }
    
    public void setTicketCost(Double ticketCost) {
        this.ticketCost = ticketCost;
    }


    @Column(name="num_tickets")
    public Integer getNumTickets() {
        return this.numTickets;
    }
    
    public void setNumTickets(Integer numTickets) {
        this.numTickets = numTickets;
    }


    @Column(name="idea_gross")
    public Integer getIdeaGross() {
        return this.ideaGross;
    }
    
    public void setIdeaGross(Integer ideaGross) {
        this.ideaGross = ideaGross;
    }


    @Column(name="idea_prizes")
    public Integer getIdeaPrizes() {
        return this.ideaPrizes;
    }
    
    public void setIdeaPrizes(Integer ideaPrizes) {
        this.ideaPrizes = ideaPrizes;
    }


    @Column(name="idea_net")
    public Integer getIdeaNet() {
        return this.ideaNet;
    }
    
    public void setIdeaNet(Integer ideaNet) {
        this.ideaNet = ideaNet;
    }


    @Column(name="dists_id_dist_id", nullable=false)
    public int getDistsIdDistId() {
        return this.distsIdDistId;
    }
    
    public void setDistsIdDistId(int distsIdDistId) {
        this.distsIdDistId = distsIdDistId;
    }


    @Column(name="mfg_id_mfg_id", nullable=false)
    public int getMfgIdMfgId() {
        return this.mfgIdMfgId;
    }
    
    public void setMfgIdMfgId(int mfgIdMfgId) {
        this.mfgIdMfgId = mfgIdMfgId;
    }


    @Column(name="Last_sale")
    public Integer getLastSale() {
        return this.lastSale;
    }
    
    public void setLastSale(Integer lastSale) {
        this.lastSale = lastSale;
    }


    @Column(name="Last_sale_allow")
    public Integer getLastSaleAllow() {
        return this.lastSaleAllow;
    }
    
    public void setLastSaleAllow(Integer lastSaleAllow) {
        this.lastSaleAllow = lastSaleAllow;
    }


    @Column(name="Prize_amt1")
    public Integer getPrizeAmt1() {
        return this.prizeAmt1;
    }
    
    public void setPrizeAmt1(Integer prizeAmt1) {
        this.prizeAmt1 = prizeAmt1;
    }


    @Column(name="Prize_amt2")
    public Integer getPrizeAmt2() {
        return this.prizeAmt2;
    }
    
    public void setPrizeAmt2(Integer prizeAmt2) {
        this.prizeAmt2 = prizeAmt2;
    }


    @Column(name="Prize_amt3")
    public Integer getPrizeAmt3() {
        return this.prizeAmt3;
    }
    
    public void setPrizeAmt3(Integer prizeAmt3) {
        this.prizeAmt3 = prizeAmt3;
    }


    @Column(name="Prize_amt4")
    public Integer getPrizeAmt4() {
        return this.prizeAmt4;
    }
    
    public void setPrizeAmt4(Integer prizeAmt4) {
        this.prizeAmt4 = prizeAmt4;
    }


    @Column(name="Prize_amt5")
    public Integer getPrizeAmt5() {
        return this.prizeAmt5;
    }
    
    public void setPrizeAmt5(Integer prizeAmt5) {
        this.prizeAmt5 = prizeAmt5;
    }


    @Column(name="Prize_amt6")
    public Integer getPrizeAmt6() {
        return this.prizeAmt6;
    }
    
    public void setPrizeAmt6(Integer prizeAmt6) {
        this.prizeAmt6 = prizeAmt6;
    }


    @Column(name="Prize_amt7")
    public Integer getPrizeAmt7() {
        return this.prizeAmt7;
    }
    
    public void setPrizeAmt7(Integer prizeAmt7) {
        this.prizeAmt7 = prizeAmt7;
    }


    @Column(name="Prize_amt8")
    public Integer getPrizeAmt8() {
        return this.prizeAmt8;
    }
    
    public void setPrizeAmt8(Integer prizeAmt8) {
        this.prizeAmt8 = prizeAmt8;
    }


    @Column(name="Prize_amt9")
    public Integer getPrizeAmt9() {
        return this.prizeAmt9;
    }
    
    public void setPrizeAmt9(Integer prizeAmt9) {
        this.prizeAmt9 = prizeAmt9;
    }


    @Column(name="Prize_amt10")
    public Integer getPrizeAmt10() {
        return this.prizeAmt10;
    }
    
    public void setPrizeAmt10(Integer prizeAmt10) {
        this.prizeAmt10 = prizeAmt10;
    }


    @Column(name="Prize_amt11")
    public Integer getPrizeAmt11() {
        return this.prizeAmt11;
    }
    
    public void setPrizeAmt11(Integer prizeAmt11) {
        this.prizeAmt11 = prizeAmt11;
    }


    @Column(name="Prize_amt12")
    public Integer getPrizeAmt12() {
        return this.prizeAmt12;
    }
    
    public void setPrizeAmt12(Integer prizeAmt12) {
        this.prizeAmt12 = prizeAmt12;
    }


    @Column(name="Prize_amt13")
    public Integer getPrizeAmt13() {
        return this.prizeAmt13;
    }
    
    public void setPrizeAmt13(Integer prizeAmt13) {
        this.prizeAmt13 = prizeAmt13;
    }


    @Column(name="Prize_amt14")
    public Integer getPrizeAmt14() {
        return this.prizeAmt14;
    }
    
    public void setPrizeAmt14(Integer prizeAmt14) {
        this.prizeAmt14 = prizeAmt14;
    }


    @Column(name="Prize_amt15")
    public Integer getPrizeAmt15() {
        return this.prizeAmt15;
    }
    
    public void setPrizeAmt15(Integer prizeAmt15) {
        this.prizeAmt15 = prizeAmt15;
    }


    @Column(name="Prize_all1")
    public Integer getPrizeAll1() {
        return this.prizeAll1;
    }
    
    public void setPrizeAll1(Integer prizeAll1) {
        this.prizeAll1 = prizeAll1;
    }


    @Column(name="Prize_all2")
    public Integer getPrizeAll2() {
        return this.prizeAll2;
    }
    
    public void setPrizeAll2(Integer prizeAll2) {
        this.prizeAll2 = prizeAll2;
    }


    @Column(name="Prize_all3")
    public Integer getPrizeAll3() {
        return this.prizeAll3;
    }
    
    public void setPrizeAll3(Integer prizeAll3) {
        this.prizeAll3 = prizeAll3;
    }


    @Column(name="Prize_all4")
    public Integer getPrizeAll4() {
        return this.prizeAll4;
    }
    
    public void setPrizeAll4(Integer prizeAll4) {
        this.prizeAll4 = prizeAll4;
    }


    @Column(name="Prize_all5")
    public Integer getPrizeAll5() {
        return this.prizeAll5;
    }
    
    public void setPrizeAll5(Integer prizeAll5) {
        this.prizeAll5 = prizeAll5;
    }


    @Column(name="Prize_all6")
    public Integer getPrizeAll6() {
        return this.prizeAll6;
    }
    
    public void setPrizeAll6(Integer prizeAll6) {
        this.prizeAll6 = prizeAll6;
    }


    @Column(name="Prize_all7")
    public Integer getPrizeAll7() {
        return this.prizeAll7;
    }
    
    public void setPrizeAll7(Integer prizeAll7) {
        this.prizeAll7 = prizeAll7;
    }


    @Column(name="Prize_all8")
    public Integer getPrizeAll8() {
        return this.prizeAll8;
    }
    
    public void setPrizeAll8(Integer prizeAll8) {
        this.prizeAll8 = prizeAll8;
    }


    @Column(name="Prize_all9")
    public Integer getPrizeAll9() {
        return this.prizeAll9;
    }
    
    public void setPrizeAll9(Integer prizeAll9) {
        this.prizeAll9 = prizeAll9;
    }


    @Column(name="Prize_all10")
    public Integer getPrizeAll10() {
        return this.prizeAll10;
    }
    
    public void setPrizeAll10(Integer prizeAll10) {
        this.prizeAll10 = prizeAll10;
    }


    @Column(name="Prize_all11")
    public Integer getPrizeAll11() {
        return this.prizeAll11;
    }
    
    public void setPrizeAll11(Integer prizeAll11) {
        this.prizeAll11 = prizeAll11;
    }


    @Column(name="Prize_all12")
    public Integer getPrizeAll12() {
        return this.prizeAll12;
    }
    
    public void setPrizeAll12(Integer prizeAll12) {
        this.prizeAll12 = prizeAll12;
    }


    @Column(name="Prize_all13")
    public Integer getPrizeAll13() {
        return this.prizeAll13;
    }
    
    public void setPrizeAll13(Integer prizeAll13) {
        this.prizeAll13 = prizeAll13;
    }


    @Column(name="Prize_all14")
    public Integer getPrizeAll14() {
        return this.prizeAll14;
    }
    
    public void setPrizeAll14(Integer prizeAll14) {
        this.prizeAll14 = prizeAll14;
    }


    @Column(name="Prize_all15")
    public Integer getPrizeAll15() {
        return this.prizeAll15;
    }
    
    public void setPrizeAll15(Integer prizeAll15) {
        this.prizeAll15 = prizeAll15;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InventoryId) ) return false;
		 InventoryId castOther = ( InventoryId ) other; 
         
		 return ( (this.getSerial()==castOther.getSerial()) || ( this.getSerial()!=null && castOther.getSerial()!=null && this.getSerial().equals(castOther.getSerial()) ) )
 && ( (this.getDatePlaced()==castOther.getDatePlaced()) || ( this.getDatePlaced()!=null && castOther.getDatePlaced()!=null && this.getDatePlaced().equals(castOther.getDatePlaced()) ) )
 && ( (this.getDateRemoved()==castOther.getDateRemoved()) || ( this.getDateRemoved()!=null && castOther.getDateRemoved()!=null && this.getDateRemoved().equals(castOther.getDateRemoved()) ) )
 && ( (this.getUnsoldAmt()==castOther.getUnsoldAmt()) || ( this.getUnsoldAmt()!=null && castOther.getUnsoldAmt()!=null && this.getUnsoldAmt().equals(castOther.getUnsoldAmt()) ) )
 && ( (this.getActualGross()==castOther.getActualGross()) || ( this.getActualGross()!=null && castOther.getActualGross()!=null && this.getActualGross().equals(castOther.getActualGross()) ) )
 && ( (this.getActualPrizes()==castOther.getActualPrizes()) || ( this.getActualPrizes()!=null && castOther.getActualPrizes()!=null && this.getActualPrizes().equals(castOther.getActualPrizes()) ) )
 && ( (this.getActualNet()==castOther.getActualNet()) || ( this.getActualNet()!=null && castOther.getActualNet()!=null && this.getActualNet().equals(castOther.getActualNet()) ) )
 && ( (this.getBin()==castOther.getBin()) || ( this.getBin()!=null && castOther.getBin()!=null && this.getBin().equals(castOther.getBin()) ) )
 && ( (this.getInplay()==castOther.getInplay()) || ( this.getInplay()!=null && castOther.getInplay()!=null && this.getInplay().equals(castOther.getInplay()) ) )
 && ( (this.getClosed()==castOther.getClosed()) || ( this.getClosed()!=null && castOther.getClosed()!=null && this.getClosed().equals(castOther.getClosed()) ) )
 && ( (this.getUnsoldTickets()==castOther.getUnsoldTickets()) || ( this.getUnsoldTickets()!=null && castOther.getUnsoldTickets()!=null && this.getUnsoldTickets().equals(castOther.getUnsoldTickets()) ) )
 && ( (this.getLastSaleRem()==castOther.getLastSaleRem()) || ( this.getLastSaleRem()!=null && castOther.getLastSaleRem()!=null && this.getLastSaleRem().equals(castOther.getLastSaleRem()) ) )
 && ( (this.getPrizeRem1()==castOther.getPrizeRem1()) || ( this.getPrizeRem1()!=null && castOther.getPrizeRem1()!=null && this.getPrizeRem1().equals(castOther.getPrizeRem1()) ) )
 && ( (this.getPrizeRem2()==castOther.getPrizeRem2()) || ( this.getPrizeRem2()!=null && castOther.getPrizeRem2()!=null && this.getPrizeRem2().equals(castOther.getPrizeRem2()) ) )
 && ( (this.getPrizeRem3()==castOther.getPrizeRem3()) || ( this.getPrizeRem3()!=null && castOther.getPrizeRem3()!=null && this.getPrizeRem3().equals(castOther.getPrizeRem3()) ) )
 && ( (this.getPrizeRem4()==castOther.getPrizeRem4()) || ( this.getPrizeRem4()!=null && castOther.getPrizeRem4()!=null && this.getPrizeRem4().equals(castOther.getPrizeRem4()) ) )
 && ( (this.getPrizeRem5()==castOther.getPrizeRem5()) || ( this.getPrizeRem5()!=null && castOther.getPrizeRem5()!=null && this.getPrizeRem5().equals(castOther.getPrizeRem5()) ) )
 && ( (this.getPrizeRem6()==castOther.getPrizeRem6()) || ( this.getPrizeRem6()!=null && castOther.getPrizeRem6()!=null && this.getPrizeRem6().equals(castOther.getPrizeRem6()) ) )
 && ( (this.getPrizeRem7()==castOther.getPrizeRem7()) || ( this.getPrizeRem7()!=null && castOther.getPrizeRem7()!=null && this.getPrizeRem7().equals(castOther.getPrizeRem7()) ) )
 && ( (this.getPrizeRem8()==castOther.getPrizeRem8()) || ( this.getPrizeRem8()!=null && castOther.getPrizeRem8()!=null && this.getPrizeRem8().equals(castOther.getPrizeRem8()) ) )
 && ( (this.getPrizeRem9()==castOther.getPrizeRem9()) || ( this.getPrizeRem9()!=null && castOther.getPrizeRem9()!=null && this.getPrizeRem9().equals(castOther.getPrizeRem9()) ) )
 && ( (this.getPrizeRem10()==castOther.getPrizeRem10()) || ( this.getPrizeRem10()!=null && castOther.getPrizeRem10()!=null && this.getPrizeRem10().equals(castOther.getPrizeRem10()) ) )
 && ( (this.getPrizeRem11()==castOther.getPrizeRem11()) || ( this.getPrizeRem11()!=null && castOther.getPrizeRem11()!=null && this.getPrizeRem11().equals(castOther.getPrizeRem11()) ) )
 && ( (this.getPrizeRem12()==castOther.getPrizeRem12()) || ( this.getPrizeRem12()!=null && castOther.getPrizeRem12()!=null && this.getPrizeRem12().equals(castOther.getPrizeRem12()) ) )
 && ( (this.getPrizeRem13()==castOther.getPrizeRem13()) || ( this.getPrizeRem13()!=null && castOther.getPrizeRem13()!=null && this.getPrizeRem13().equals(castOther.getPrizeRem13()) ) )
 && ( (this.getPrizeRem14()==castOther.getPrizeRem14()) || ( this.getPrizeRem14()!=null && castOther.getPrizeRem14()!=null && this.getPrizeRem14().equals(castOther.getPrizeRem14()) ) )
 && ( (this.getPrizeRem15()==castOther.getPrizeRem15()) || ( this.getPrizeRem15()!=null && castOther.getPrizeRem15()!=null && this.getPrizeRem15().equals(castOther.getPrizeRem15()) ) )
 && ( (this.getGameTemplatesPartNum()==castOther.getGameTemplatesPartNum()) || ( this.getGameTemplatesPartNum()!=null && castOther.getGameTemplatesPartNum()!=null && this.getGameTemplatesPartNum().equals(castOther.getGameTemplatesPartNum()) ) )
 && ( (this.getDatePurch()==castOther.getDatePurch()) || ( this.getDatePurch()!=null && castOther.getDatePurch()!=null && this.getDatePurch().equals(castOther.getDatePurch()) ) )
 && ( (this.getInvoiceNum()==castOther.getInvoiceNum()) || ( this.getInvoiceNum()!=null && castOther.getInvoiceNum()!=null && this.getInvoiceNum().equals(castOther.getInvoiceNum()) ) )
 && ( (this.getPartNum()==castOther.getPartNum()) || ( this.getPartNum()!=null && castOther.getPartNum()!=null && this.getPartNum().equals(castOther.getPartNum()) ) )
 && ( (this.getGameName()==castOther.getGameName()) || ( this.getGameName()!=null && castOther.getGameName()!=null && this.getGameName().equals(castOther.getGameName()) ) )
 && ( (this.getGameCost()==castOther.getGameCost()) || ( this.getGameCost()!=null && castOther.getGameCost()!=null && this.getGameCost().equals(castOther.getGameCost()) ) )
 && ( (this.getTicketCost()==castOther.getTicketCost()) || ( this.getTicketCost()!=null && castOther.getTicketCost()!=null && this.getTicketCost().equals(castOther.getTicketCost()) ) )
 && ( (this.getNumTickets()==castOther.getNumTickets()) || ( this.getNumTickets()!=null && castOther.getNumTickets()!=null && this.getNumTickets().equals(castOther.getNumTickets()) ) )
 && ( (this.getIdeaGross()==castOther.getIdeaGross()) || ( this.getIdeaGross()!=null && castOther.getIdeaGross()!=null && this.getIdeaGross().equals(castOther.getIdeaGross()) ) )
 && ( (this.getIdeaPrizes()==castOther.getIdeaPrizes()) || ( this.getIdeaPrizes()!=null && castOther.getIdeaPrizes()!=null && this.getIdeaPrizes().equals(castOther.getIdeaPrizes()) ) )
 && ( (this.getIdeaNet()==castOther.getIdeaNet()) || ( this.getIdeaNet()!=null && castOther.getIdeaNet()!=null && this.getIdeaNet().equals(castOther.getIdeaNet()) ) )
 && (this.getDistsIdDistId()==castOther.getDistsIdDistId())
 && (this.getMfgIdMfgId()==castOther.getMfgIdMfgId())
 && ( (this.getLastSale()==castOther.getLastSale()) || ( this.getLastSale()!=null && castOther.getLastSale()!=null && this.getLastSale().equals(castOther.getLastSale()) ) )
 && ( (this.getLastSaleAllow()==castOther.getLastSaleAllow()) || ( this.getLastSaleAllow()!=null && castOther.getLastSaleAllow()!=null && this.getLastSaleAllow().equals(castOther.getLastSaleAllow()) ) )
 && ( (this.getPrizeAmt1()==castOther.getPrizeAmt1()) || ( this.getPrizeAmt1()!=null && castOther.getPrizeAmt1()!=null && this.getPrizeAmt1().equals(castOther.getPrizeAmt1()) ) )
 && ( (this.getPrizeAmt2()==castOther.getPrizeAmt2()) || ( this.getPrizeAmt2()!=null && castOther.getPrizeAmt2()!=null && this.getPrizeAmt2().equals(castOther.getPrizeAmt2()) ) )
 && ( (this.getPrizeAmt3()==castOther.getPrizeAmt3()) || ( this.getPrizeAmt3()!=null && castOther.getPrizeAmt3()!=null && this.getPrizeAmt3().equals(castOther.getPrizeAmt3()) ) )
 && ( (this.getPrizeAmt4()==castOther.getPrizeAmt4()) || ( this.getPrizeAmt4()!=null && castOther.getPrizeAmt4()!=null && this.getPrizeAmt4().equals(castOther.getPrizeAmt4()) ) )
 && ( (this.getPrizeAmt5()==castOther.getPrizeAmt5()) || ( this.getPrizeAmt5()!=null && castOther.getPrizeAmt5()!=null && this.getPrizeAmt5().equals(castOther.getPrizeAmt5()) ) )
 && ( (this.getPrizeAmt6()==castOther.getPrizeAmt6()) || ( this.getPrizeAmt6()!=null && castOther.getPrizeAmt6()!=null && this.getPrizeAmt6().equals(castOther.getPrizeAmt6()) ) )
 && ( (this.getPrizeAmt7()==castOther.getPrizeAmt7()) || ( this.getPrizeAmt7()!=null && castOther.getPrizeAmt7()!=null && this.getPrizeAmt7().equals(castOther.getPrizeAmt7()) ) )
 && ( (this.getPrizeAmt8()==castOther.getPrizeAmt8()) || ( this.getPrizeAmt8()!=null && castOther.getPrizeAmt8()!=null && this.getPrizeAmt8().equals(castOther.getPrizeAmt8()) ) )
 && ( (this.getPrizeAmt9()==castOther.getPrizeAmt9()) || ( this.getPrizeAmt9()!=null && castOther.getPrizeAmt9()!=null && this.getPrizeAmt9().equals(castOther.getPrizeAmt9()) ) )
 && ( (this.getPrizeAmt10()==castOther.getPrizeAmt10()) || ( this.getPrizeAmt10()!=null && castOther.getPrizeAmt10()!=null && this.getPrizeAmt10().equals(castOther.getPrizeAmt10()) ) )
 && ( (this.getPrizeAmt11()==castOther.getPrizeAmt11()) || ( this.getPrizeAmt11()!=null && castOther.getPrizeAmt11()!=null && this.getPrizeAmt11().equals(castOther.getPrizeAmt11()) ) )
 && ( (this.getPrizeAmt12()==castOther.getPrizeAmt12()) || ( this.getPrizeAmt12()!=null && castOther.getPrizeAmt12()!=null && this.getPrizeAmt12().equals(castOther.getPrizeAmt12()) ) )
 && ( (this.getPrizeAmt13()==castOther.getPrizeAmt13()) || ( this.getPrizeAmt13()!=null && castOther.getPrizeAmt13()!=null && this.getPrizeAmt13().equals(castOther.getPrizeAmt13()) ) )
 && ( (this.getPrizeAmt14()==castOther.getPrizeAmt14()) || ( this.getPrizeAmt14()!=null && castOther.getPrizeAmt14()!=null && this.getPrizeAmt14().equals(castOther.getPrizeAmt14()) ) )
 && ( (this.getPrizeAmt15()==castOther.getPrizeAmt15()) || ( this.getPrizeAmt15()!=null && castOther.getPrizeAmt15()!=null && this.getPrizeAmt15().equals(castOther.getPrizeAmt15()) ) )
 && ( (this.getPrizeAll1()==castOther.getPrizeAll1()) || ( this.getPrizeAll1()!=null && castOther.getPrizeAll1()!=null && this.getPrizeAll1().equals(castOther.getPrizeAll1()) ) )
 && ( (this.getPrizeAll2()==castOther.getPrizeAll2()) || ( this.getPrizeAll2()!=null && castOther.getPrizeAll2()!=null && this.getPrizeAll2().equals(castOther.getPrizeAll2()) ) )
 && ( (this.getPrizeAll3()==castOther.getPrizeAll3()) || ( this.getPrizeAll3()!=null && castOther.getPrizeAll3()!=null && this.getPrizeAll3().equals(castOther.getPrizeAll3()) ) )
 && ( (this.getPrizeAll4()==castOther.getPrizeAll4()) || ( this.getPrizeAll4()!=null && castOther.getPrizeAll4()!=null && this.getPrizeAll4().equals(castOther.getPrizeAll4()) ) )
 && ( (this.getPrizeAll5()==castOther.getPrizeAll5()) || ( this.getPrizeAll5()!=null && castOther.getPrizeAll5()!=null && this.getPrizeAll5().equals(castOther.getPrizeAll5()) ) )
 && ( (this.getPrizeAll6()==castOther.getPrizeAll6()) || ( this.getPrizeAll6()!=null && castOther.getPrizeAll6()!=null && this.getPrizeAll6().equals(castOther.getPrizeAll6()) ) )
 && ( (this.getPrizeAll7()==castOther.getPrizeAll7()) || ( this.getPrizeAll7()!=null && castOther.getPrizeAll7()!=null && this.getPrizeAll7().equals(castOther.getPrizeAll7()) ) )
 && ( (this.getPrizeAll8()==castOther.getPrizeAll8()) || ( this.getPrizeAll8()!=null && castOther.getPrizeAll8()!=null && this.getPrizeAll8().equals(castOther.getPrizeAll8()) ) )
 && ( (this.getPrizeAll9()==castOther.getPrizeAll9()) || ( this.getPrizeAll9()!=null && castOther.getPrizeAll9()!=null && this.getPrizeAll9().equals(castOther.getPrizeAll9()) ) )
 && ( (this.getPrizeAll10()==castOther.getPrizeAll10()) || ( this.getPrizeAll10()!=null && castOther.getPrizeAll10()!=null && this.getPrizeAll10().equals(castOther.getPrizeAll10()) ) )
 && ( (this.getPrizeAll11()==castOther.getPrizeAll11()) || ( this.getPrizeAll11()!=null && castOther.getPrizeAll11()!=null && this.getPrizeAll11().equals(castOther.getPrizeAll11()) ) )
 && ( (this.getPrizeAll12()==castOther.getPrizeAll12()) || ( this.getPrizeAll12()!=null && castOther.getPrizeAll12()!=null && this.getPrizeAll12().equals(castOther.getPrizeAll12()) ) )
 && ( (this.getPrizeAll13()==castOther.getPrizeAll13()) || ( this.getPrizeAll13()!=null && castOther.getPrizeAll13()!=null && this.getPrizeAll13().equals(castOther.getPrizeAll13()) ) )
 && ( (this.getPrizeAll14()==castOther.getPrizeAll14()) || ( this.getPrizeAll14()!=null && castOther.getPrizeAll14()!=null && this.getPrizeAll14().equals(castOther.getPrizeAll14()) ) )
 && ( (this.getPrizeAll15()==castOther.getPrizeAll15()) || ( this.getPrizeAll15()!=null && castOther.getPrizeAll15()!=null && this.getPrizeAll15().equals(castOther.getPrizeAll15()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSerial() == null ? 0 : this.getSerial().hashCode() );
         result = 37 * result + ( getDatePlaced() == null ? 0 : this.getDatePlaced().hashCode() );
         result = 37 * result + ( getDateRemoved() == null ? 0 : this.getDateRemoved().hashCode() );
         result = 37 * result + ( getUnsoldAmt() == null ? 0 : this.getUnsoldAmt().hashCode() );
         result = 37 * result + ( getActualGross() == null ? 0 : this.getActualGross().hashCode() );
         result = 37 * result + ( getActualPrizes() == null ? 0 : this.getActualPrizes().hashCode() );
         result = 37 * result + ( getActualNet() == null ? 0 : this.getActualNet().hashCode() );
         result = 37 * result + ( getBin() == null ? 0 : this.getBin().hashCode() );
         result = 37 * result + ( getInplay() == null ? 0 : this.getInplay().hashCode() );
         result = 37 * result + ( getClosed() == null ? 0 : this.getClosed().hashCode() );
         result = 37 * result + ( getUnsoldTickets() == null ? 0 : this.getUnsoldTickets().hashCode() );
         result = 37 * result + ( getLastSaleRem() == null ? 0 : this.getLastSaleRem().hashCode() );
         result = 37 * result + ( getPrizeRem1() == null ? 0 : this.getPrizeRem1().hashCode() );
         result = 37 * result + ( getPrizeRem2() == null ? 0 : this.getPrizeRem2().hashCode() );
         result = 37 * result + ( getPrizeRem3() == null ? 0 : this.getPrizeRem3().hashCode() );
         result = 37 * result + ( getPrizeRem4() == null ? 0 : this.getPrizeRem4().hashCode() );
         result = 37 * result + ( getPrizeRem5() == null ? 0 : this.getPrizeRem5().hashCode() );
         result = 37 * result + ( getPrizeRem6() == null ? 0 : this.getPrizeRem6().hashCode() );
         result = 37 * result + ( getPrizeRem7() == null ? 0 : this.getPrizeRem7().hashCode() );
         result = 37 * result + ( getPrizeRem8() == null ? 0 : this.getPrizeRem8().hashCode() );
         result = 37 * result + ( getPrizeRem9() == null ? 0 : this.getPrizeRem9().hashCode() );
         result = 37 * result + ( getPrizeRem10() == null ? 0 : this.getPrizeRem10().hashCode() );
         result = 37 * result + ( getPrizeRem11() == null ? 0 : this.getPrizeRem11().hashCode() );
         result = 37 * result + ( getPrizeRem12() == null ? 0 : this.getPrizeRem12().hashCode() );
         result = 37 * result + ( getPrizeRem13() == null ? 0 : this.getPrizeRem13().hashCode() );
         result = 37 * result + ( getPrizeRem14() == null ? 0 : this.getPrizeRem14().hashCode() );
         result = 37 * result + ( getPrizeRem15() == null ? 0 : this.getPrizeRem15().hashCode() );
         result = 37 * result + ( getGameTemplatesPartNum() == null ? 0 : this.getGameTemplatesPartNum().hashCode() );
         result = 37 * result + ( getDatePurch() == null ? 0 : this.getDatePurch().hashCode() );
         result = 37 * result + ( getInvoiceNum() == null ? 0 : this.getInvoiceNum().hashCode() );
         result = 37 * result + ( getPartNum() == null ? 0 : this.getPartNum().hashCode() );
         result = 37 * result + ( getGameName() == null ? 0 : this.getGameName().hashCode() );
         result = 37 * result + ( getGameCost() == null ? 0 : this.getGameCost().hashCode() );
         result = 37 * result + ( getTicketCost() == null ? 0 : this.getTicketCost().hashCode() );
         result = 37 * result + ( getNumTickets() == null ? 0 : this.getNumTickets().hashCode() );
         result = 37 * result + ( getIdeaGross() == null ? 0 : this.getIdeaGross().hashCode() );
         result = 37 * result + ( getIdeaPrizes() == null ? 0 : this.getIdeaPrizes().hashCode() );
         result = 37 * result + ( getIdeaNet() == null ? 0 : this.getIdeaNet().hashCode() );
         result = 37 * result + this.getDistsIdDistId();
         result = 37 * result + this.getMfgIdMfgId();
         result = 37 * result + ( getLastSale() == null ? 0 : this.getLastSale().hashCode() );
         result = 37 * result + ( getLastSaleAllow() == null ? 0 : this.getLastSaleAllow().hashCode() );
         result = 37 * result + ( getPrizeAmt1() == null ? 0 : this.getPrizeAmt1().hashCode() );
         result = 37 * result + ( getPrizeAmt2() == null ? 0 : this.getPrizeAmt2().hashCode() );
         result = 37 * result + ( getPrizeAmt3() == null ? 0 : this.getPrizeAmt3().hashCode() );
         result = 37 * result + ( getPrizeAmt4() == null ? 0 : this.getPrizeAmt4().hashCode() );
         result = 37 * result + ( getPrizeAmt5() == null ? 0 : this.getPrizeAmt5().hashCode() );
         result = 37 * result + ( getPrizeAmt6() == null ? 0 : this.getPrizeAmt6().hashCode() );
         result = 37 * result + ( getPrizeAmt7() == null ? 0 : this.getPrizeAmt7().hashCode() );
         result = 37 * result + ( getPrizeAmt8() == null ? 0 : this.getPrizeAmt8().hashCode() );
         result = 37 * result + ( getPrizeAmt9() == null ? 0 : this.getPrizeAmt9().hashCode() );
         result = 37 * result + ( getPrizeAmt10() == null ? 0 : this.getPrizeAmt10().hashCode() );
         result = 37 * result + ( getPrizeAmt11() == null ? 0 : this.getPrizeAmt11().hashCode() );
         result = 37 * result + ( getPrizeAmt12() == null ? 0 : this.getPrizeAmt12().hashCode() );
         result = 37 * result + ( getPrizeAmt13() == null ? 0 : this.getPrizeAmt13().hashCode() );
         result = 37 * result + ( getPrizeAmt14() == null ? 0 : this.getPrizeAmt14().hashCode() );
         result = 37 * result + ( getPrizeAmt15() == null ? 0 : this.getPrizeAmt15().hashCode() );
         result = 37 * result + ( getPrizeAll1() == null ? 0 : this.getPrizeAll1().hashCode() );
         result = 37 * result + ( getPrizeAll2() == null ? 0 : this.getPrizeAll2().hashCode() );
         result = 37 * result + ( getPrizeAll3() == null ? 0 : this.getPrizeAll3().hashCode() );
         result = 37 * result + ( getPrizeAll4() == null ? 0 : this.getPrizeAll4().hashCode() );
         result = 37 * result + ( getPrizeAll5() == null ? 0 : this.getPrizeAll5().hashCode() );
         result = 37 * result + ( getPrizeAll6() == null ? 0 : this.getPrizeAll6().hashCode() );
         result = 37 * result + ( getPrizeAll7() == null ? 0 : this.getPrizeAll7().hashCode() );
         result = 37 * result + ( getPrizeAll8() == null ? 0 : this.getPrizeAll8().hashCode() );
         result = 37 * result + ( getPrizeAll9() == null ? 0 : this.getPrizeAll9().hashCode() );
         result = 37 * result + ( getPrizeAll10() == null ? 0 : this.getPrizeAll10().hashCode() );
         result = 37 * result + ( getPrizeAll11() == null ? 0 : this.getPrizeAll11().hashCode() );
         result = 37 * result + ( getPrizeAll12() == null ? 0 : this.getPrizeAll12().hashCode() );
         result = 37 * result + ( getPrizeAll13() == null ? 0 : this.getPrizeAll13().hashCode() );
         result = 37 * result + ( getPrizeAll14() == null ? 0 : this.getPrizeAll14().hashCode() );
         result = 37 * result + ( getPrizeAll15() == null ? 0 : this.getPrizeAll15().hashCode() );
         return result;
   }   


}


