package entity;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Locations generated by hbm2java
 */
public class Locations  implements java.io.Serializable {


     private Integer locId;
     private String name;
     private String address;
     private String state;
     private String city;
     private Set tillTapes = new HashSet(0);

    public Locations() {
    }

    public Locations(String name, String address, String state, String city, Set tillTapes) {
       this.name = name;
       this.address = address;
       this.state = state;
       this.city = city;
       this.tillTapes = tillTapes;
    }
   
    public Integer getLocId() {
        return this.locId;
    }
    
    public void setLocId(Integer locId) {
        this.locId = locId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Set getTillTapes() {
        return this.tillTapes;
    }
    
    public void setTillTapes(Set tillTapes) {
        this.tillTapes = tillTapes;
    }




}


