package entity;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * MfgId generated by hbm2java
 */
public class MfgId  implements java.io.Serializable {


     private Integer mfgId;
     private String name;
     private String mfgAbr;
     private Set gameTemplateses = new HashSet(0);

    public MfgId() {
    }

    public MfgId(String name, String mfgAbr, Set gameTemplateses) {
       this.name = name;
       this.mfgAbr = mfgAbr;
       this.gameTemplateses = gameTemplateses;
    }
   
    public Integer getMfgId() {
        return this.mfgId;
    }
    
    public void setMfgId(Integer mfgId) {
        this.mfgId = mfgId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMfgAbr() {
        return this.mfgAbr;
    }
    
    public void setMfgAbr(String mfgAbr) {
        this.mfgAbr = mfgAbr;
    }
    public Set getGameTemplateses() {
        return this.gameTemplateses;
    }
    
    public void setGameTemplateses(Set gameTemplateses) {
        this.gameTemplateses = gameTemplateses;
    }

    @Override
    public String toString() {
        return "MfgId{" + "mfgId=" + mfgId + ", name=" + name + ", mfgAbr=" + mfgAbr + ", gameTemplateses=" + gameTemplateses + '}';
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + Objects.hashCode(this.mfgId);
        hash = 59 * hash + Objects.hashCode(this.name);
        hash = 59 * hash + Objects.hashCode(this.mfgAbr);
        hash = 59 * hash + Objects.hashCode(this.gameTemplateses);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final MfgId other = (MfgId) obj;
        if (!Objects.equals(this.mfgId, other.mfgId)) {
            return false;
        }
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        if (!Objects.equals(this.mfgAbr, other.mfgAbr)) {
            return false;
        }
        if (!Objects.equals(this.gameTemplateses, other.gameTemplateses)) {
            return false;
        }
        return true;
    }




}


