package entity;
// Generated Oct 11, 2015 7:56:58 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MonthlyId generated by hbm2java
 */
@Embeddable
public class MonthlyId  implements java.io.Serializable {


     private Double grossSales;
     private Double grossPrizes;
     private Double grossNet;

    public MonthlyId() {
    }

    public MonthlyId(Double grossSales, Double grossPrizes, Double grossNet) {
       this.grossSales = grossSales;
       this.grossPrizes = grossPrizes;
       this.grossNet = grossNet;
    }
   


    @Column(name="Gross Sales", precision=22, scale=0)
    public Double getGrossSales() {
        return this.grossSales;
    }
    
    public void setGrossSales(Double grossSales) {
        this.grossSales = grossSales;
    }


    @Column(name="Gross Prizes", precision=22, scale=0)
    public Double getGrossPrizes() {
        return this.grossPrizes;
    }
    
    public void setGrossPrizes(Double grossPrizes) {
        this.grossPrizes = grossPrizes;
    }


    @Column(name="Gross Net", precision=22, scale=0)
    public Double getGrossNet() {
        return this.grossNet;
    }
    
    public void setGrossNet(Double grossNet) {
        this.grossNet = grossNet;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MonthlyId) ) return false;
		 MonthlyId castOther = ( MonthlyId ) other; 
         
		 return ( (this.getGrossSales()==castOther.getGrossSales()) || ( this.getGrossSales()!=null && castOther.getGrossSales()!=null && this.getGrossSales().equals(castOther.getGrossSales()) ) )
 && ( (this.getGrossPrizes()==castOther.getGrossPrizes()) || ( this.getGrossPrizes()!=null && castOther.getGrossPrizes()!=null && this.getGrossPrizes().equals(castOther.getGrossPrizes()) ) )
 && ( (this.getGrossNet()==castOther.getGrossNet()) || ( this.getGrossNet()!=null && castOther.getGrossNet()!=null && this.getGrossNet().equals(castOther.getGrossNet()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGrossSales() == null ? 0 : this.getGrossSales().hashCode() );
         result = 37 * result + ( getGrossPrizes() == null ? 0 : this.getGrossPrizes().hashCode() );
         result = 37 * result + ( getGrossNet() == null ? 0 : this.getGrossNet().hashCode() );
         return result;
   }   


}


