package entity;
// Generated Oct 11, 2015 7:56:58 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Monthly generated by hbm2java
 */
@Entity
@Table(name="monthly"
    ,catalog="fire_tickets"
)
public class Monthly  implements java.io.Serializable {


     private MonthlyId id;

    public Monthly() {
    }

    public Monthly(MonthlyId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="grossSales", column=@Column(name="Gross Sales", precision=22, scale=0) ), 
        @AttributeOverride(name="grossPrizes", column=@Column(name="Gross Prizes", precision=22, scale=0) ), 
        @AttributeOverride(name="grossNet", column=@Column(name="Gross Net", precision=22, scale=0) ) } )
    public MonthlyId getId() {
        return this.id;
    }
    
    public void setId(MonthlyId id) {
        this.id = id;
    }




}


