package entity;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SaleSessions generated by hbm2java
 */
public class SaleSessions  implements java.io.Serializable {


     private Integer id;
     private String startBank;
     private String grossSales;
     private String grossPrizes;
     private String grossNet;
     private Double currentbank;
     private Double endingbank;
     private Date date;

    public SaleSessions() {
    }

    public SaleSessions(String startBank, String grossSales, String grossPrizes, String grossNet, Double currentbank, Double endingbank, Date date) {
       this.startBank = startBank;
       this.grossSales = grossSales;
       this.grossPrizes = grossPrizes;
       this.grossNet = grossNet;
       this.currentbank = currentbank;
       this.endingbank = endingbank;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStartBank() {
        return this.startBank;
    }
    
    public void setStartBank(String startBank) {
        this.startBank = startBank;
    }
    public String getGrossSales() {
        return this.grossSales;
    }
    
    public void setGrossSales(String grossSales) {
        this.grossSales = grossSales;
    }
    public String getGrossPrizes() {
        return this.grossPrizes;
    }
    
    public void setGrossPrizes(String grossPrizes) {
        this.grossPrizes = grossPrizes;
    }
    public String getGrossNet() {
        return this.grossNet;
    }
    
    public void setGrossNet(String grossNet) {
        this.grossNet = grossNet;
    }
    public Double getCurrentbank() {
        return this.currentbank;
    }
    
    public void setCurrentbank(Double currentbank) {
        this.currentbank = currentbank;
    }
    public Double getEndingbank() {
        return this.endingbank;
    }
    
    public void setEndingbank(Double endingbank) {
        this.endingbank = endingbank;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


