package entity;
// Generated Oct 11, 2015 7:56:58 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SaleSessions generated by hbm2java
 */
@Entity
@Table(name="sale_sessions"
    ,catalog="fire_tickets"
)
public class SaleSessions  implements java.io.Serializable {


     private Integer id;
     private Double startBank;
     private Double grossSales;
     private Double grossPrizes;
     private Double grossNet;
     private Double currentbank;
     private Double endingbank;
     private Date date;

    public SaleSessions() {
    }

    public SaleSessions(Double startBank, Double grossSales, Double grossPrizes, Double grossNet, Double currentbank, Double endingbank, Date date) {
       this.startBank = startBank;
       this.grossSales = grossSales;
       this.grossPrizes = grossPrizes;
       this.grossNet = grossNet;
       this.currentbank = currentbank;
       this.endingbank = endingbank;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="start_bank", precision=22, scale=0)
    public Double getStartBank() {
        return this.startBank;
    }
    
    public void setStartBank(Double startBank) {
        this.startBank = startBank;
    }

    
    @Column(name="gross_sales", precision=22, scale=0)
    public Double getGrossSales() {
        return this.grossSales;
    }
    
    public void setGrossSales(Double grossSales) {
        this.grossSales = grossSales;
    }

    
    @Column(name="gross_prizes", precision=22, scale=0)
    public Double getGrossPrizes() {
        return this.grossPrizes;
    }
    
    public void setGrossPrizes(Double grossPrizes) {
        this.grossPrizes = grossPrizes;
    }

    
    @Column(name="gross_net", precision=22, scale=0)
    public Double getGrossNet() {
        return this.grossNet;
    }
    
    public void setGrossNet(Double grossNet) {
        this.grossNet = grossNet;
    }

    
    @Column(name="currentbank", precision=22, scale=0)
    public Double getCurrentbank() {
        return this.currentbank;
    }
    
    public void setCurrentbank(Double currentbank) {
        this.currentbank = currentbank;
    }

    
    @Column(name="endingbank", precision=22, scale=0)
    public Double getEndingbank() {
        return this.endingbank;
    }
    
    public void setEndingbank(Double endingbank) {
        this.endingbank = endingbank;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


