package entity;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1



/**
 * TicketsId generated by hbm2java
 */
public class TicketsId  implements java.io.Serializable {


     private String serial;
     private String gameTemplatesPartNum;

    public TicketsId() {
    }

    public TicketsId(String serial, String gameTemplatesPartNum) {
       this.serial = serial;
       this.gameTemplatesPartNum = gameTemplatesPartNum;
    }
   
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }
    public String getGameTemplatesPartNum() {
        return this.gameTemplatesPartNum;
    }
    
    public void setGameTemplatesPartNum(String gameTemplatesPartNum) {
        this.gameTemplatesPartNum = gameTemplatesPartNum;
    }




}


