package entity;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tickets generated by hbm2java
 */
public class Tickets  implements java.io.Serializable {


     private TicketsId id;
     private Date datePlaced;
     private Date dateRemoved;
     private Integer unsoldAmt;
     private Integer actualGross;
     private Integer actualPrizes;
     private Integer actualNet;
     private Integer bin;
     private Boolean inplay;
     private Integer closed;
     private Integer unsoldTickets;
     private Byte lastSaleRem;
     private Integer prizeRem1;
     private Integer prizeRem2;
     private Integer prizeRem3;
     private Integer prizeRem4;
     private Integer prizeRem5;
     private Integer prizeRem6;
     private Integer prizeRem7;
     private Integer prizeRem8;
     private Integer prizeRem9;
     private Integer prizeRem10;
     private Integer prizeRem11;
     private Integer prizeRem12;
     private Integer prizeRem13;
     private Integer prizeRem14;
     private Integer prizeRem15;
     private Date datePurch;
     private String invoiceNum;

    public Tickets() {
    }

	
    public Tickets(TicketsId id) {
        this.id = id;
    }
    public Tickets(TicketsId id, Date datePlaced, Date dateRemoved, Integer unsoldAmt, Integer actualGross, Integer actualPrizes, Integer actualNet, Integer bin, Boolean inplay, Integer closed, Integer unsoldTickets, Byte lastSaleRem, Integer prizeRem1, Integer prizeRem2, Integer prizeRem3, Integer prizeRem4, Integer prizeRem5, Integer prizeRem6, Integer prizeRem7, Integer prizeRem8, Integer prizeRem9, Integer prizeRem10, Integer prizeRem11, Integer prizeRem12, Integer prizeRem13, Integer prizeRem14, Integer prizeRem15, Date datePurch, String invoiceNum) {
       this.id = id;
       this.datePlaced = datePlaced;
       this.dateRemoved = dateRemoved;
       this.unsoldAmt = unsoldAmt;
       this.actualGross = actualGross;
       this.actualPrizes = actualPrizes;
       this.actualNet = actualNet;
       this.bin = bin;
       this.inplay = inplay;
       this.closed = closed;
       this.unsoldTickets = unsoldTickets;
       this.lastSaleRem = lastSaleRem;
       this.prizeRem1 = prizeRem1;
       this.prizeRem2 = prizeRem2;
       this.prizeRem3 = prizeRem3;
       this.prizeRem4 = prizeRem4;
       this.prizeRem5 = prizeRem5;
       this.prizeRem6 = prizeRem6;
       this.prizeRem7 = prizeRem7;
       this.prizeRem8 = prizeRem8;
       this.prizeRem9 = prizeRem9;
       this.prizeRem10 = prizeRem10;
       this.prizeRem11 = prizeRem11;
       this.prizeRem12 = prizeRem12;
       this.prizeRem13 = prizeRem13;
       this.prizeRem14 = prizeRem14;
       this.prizeRem15 = prizeRem15;
       this.datePurch = datePurch;
       this.invoiceNum = invoiceNum;
    }
   
    public TicketsId getId() {
        return this.id;
    }
    
    public void setId(TicketsId id) {
        this.id = id;
    }
    public Date getDatePlaced() {
        return this.datePlaced;
    }
    
    public void setDatePlaced(Date datePlaced) {
        this.datePlaced = datePlaced;
    }
    public Date getDateRemoved() {
        return this.dateRemoved;
    }
    
    public void setDateRemoved(Date dateRemoved) {
        this.dateRemoved = dateRemoved;
    }
    public Integer getUnsoldAmt() {
        return this.unsoldAmt;
    }
    
    public void setUnsoldAmt(Integer unsoldAmt) {
        this.unsoldAmt = unsoldAmt;
    }
    public Integer getActualGross() {
        return this.actualGross;
    }
    
    public void setActualGross(Integer actualGross) {
        this.actualGross = actualGross;
    }
    public Integer getActualPrizes() {
        return this.actualPrizes;
    }
    
    public void setActualPrizes(Integer actualPrizes) {
        this.actualPrizes = actualPrizes;
    }
    public Integer getActualNet() {
        return this.actualNet;
    }
    
    public void setActualNet(Integer actualNet) {
        this.actualNet = actualNet;
    }
    public Integer getBin() {
        return this.bin;
    }
    
    public void setBin(Integer bin) {
        this.bin = bin;
    }
    public Boolean getInplay() {
        return this.inplay;
    }
    
    public void setInplay(Boolean inplay) {
        this.inplay = inplay;
    }
    public Integer getClosed() {
        return this.closed;
    }
    
    public void setClosed(Integer closed) {
        this.closed = closed;
    }
    public Integer getUnsoldTickets() {
        return this.unsoldTickets;
    }
    
    public void setUnsoldTickets(Integer unsoldTickets) {
        this.unsoldTickets = unsoldTickets;
    }
    public Byte getLastSaleRem() {
        return this.lastSaleRem;
    }
    
    public void setLastSaleRem(Byte lastSaleRem) {
        this.lastSaleRem = lastSaleRem;
    }
    public Integer getPrizeRem1() {
        return this.prizeRem1;
    }
    
    public void setPrizeRem1(Integer prizeRem1) {
        this.prizeRem1 = prizeRem1;
    }
    public Integer getPrizeRem2() {
        return this.prizeRem2;
    }
    
    public void setPrizeRem2(Integer prizeRem2) {
        this.prizeRem2 = prizeRem2;
    }
    public Integer getPrizeRem3() {
        return this.prizeRem3;
    }
    
    public void setPrizeRem3(Integer prizeRem3) {
        this.prizeRem3 = prizeRem3;
    }
    public Integer getPrizeRem4() {
        return this.prizeRem4;
    }
    
    public void setPrizeRem4(Integer prizeRem4) {
        this.prizeRem4 = prizeRem4;
    }
    public Integer getPrizeRem5() {
        return this.prizeRem5;
    }
    
    public void setPrizeRem5(Integer prizeRem5) {
        this.prizeRem5 = prizeRem5;
    }
    public Integer getPrizeRem6() {
        return this.prizeRem6;
    }
    
    public void setPrizeRem6(Integer prizeRem6) {
        this.prizeRem6 = prizeRem6;
    }
    public Integer getPrizeRem7() {
        return this.prizeRem7;
    }
    
    public void setPrizeRem7(Integer prizeRem7) {
        this.prizeRem7 = prizeRem7;
    }
    public Integer getPrizeRem8() {
        return this.prizeRem8;
    }
    
    public void setPrizeRem8(Integer prizeRem8) {
        this.prizeRem8 = prizeRem8;
    }
    public Integer getPrizeRem9() {
        return this.prizeRem9;
    }
    
    public void setPrizeRem9(Integer prizeRem9) {
        this.prizeRem9 = prizeRem9;
    }
    public Integer getPrizeRem10() {
        return this.prizeRem10;
    }
    
    public void setPrizeRem10(Integer prizeRem10) {
        this.prizeRem10 = prizeRem10;
    }
    public Integer getPrizeRem11() {
        return this.prizeRem11;
    }
    
    public void setPrizeRem11(Integer prizeRem11) {
        this.prizeRem11 = prizeRem11;
    }
    public Integer getPrizeRem12() {
        return this.prizeRem12;
    }
    
    public void setPrizeRem12(Integer prizeRem12) {
        this.prizeRem12 = prizeRem12;
    }
    public Integer getPrizeRem13() {
        return this.prizeRem13;
    }
    
    public void setPrizeRem13(Integer prizeRem13) {
        this.prizeRem13 = prizeRem13;
    }
    public Integer getPrizeRem14() {
        return this.prizeRem14;
    }
    
    public void setPrizeRem14(Integer prizeRem14) {
        this.prizeRem14 = prizeRem14;
    }
    public Integer getPrizeRem15() {
        return this.prizeRem15;
    }
    
    public void setPrizeRem15(Integer prizeRem15) {
        this.prizeRem15 = prizeRem15;
    }
    public Date getDatePurch() {
        return this.datePurch;
    }
    
    public void setDatePurch(Date datePurch) {
        this.datePurch = datePurch;
    }
    public String getInvoiceNum() {
        return this.invoiceNum;
    }
    
    public void setInvoiceNum(String invoiceNum) {
        this.invoiceNum = invoiceNum;
    }




}


