package entity;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * TicketsId generated by hbm2java
 */
public class TicketsId  implements java.io.Serializable {


     private String serial;
     private String gameTemplatesPartNum;

    public TicketsId() {
    }

    public TicketsId(String serial, String gameTemplatesPartNum) {
       this.serial = serial;
       this.gameTemplatesPartNum = gameTemplatesPartNum;
    }
   
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }
    public String getGameTemplatesPartNum() {
        return this.gameTemplatesPartNum;
    }
    
    public void setGameTemplatesPartNum(String gameTemplatesPartNum) {
        this.gameTemplatesPartNum = gameTemplatesPartNum;
    }

    @Override
    public String toString() {
        return "TicketsId{" + "serial=" + serial + ", gameTemplatesPartNum=" + gameTemplatesPartNum + '}';
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 41 * hash + Objects.hashCode(this.serial);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TicketsId other = (TicketsId) obj;
        if (!Objects.equals(this.serial, other.serial)) {
            return false;
        }
        if (!Objects.equals(this.gameTemplatesPartNum, other.gameTemplatesPartNum)) {
            return false;
        }
        return true;
    }




}


