package entity;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1



/**
 * TillTapeId generated by hbm2java
 */
public class TillTapeId  implements java.io.Serializable {


     private int TId;
     private int usersUserId;
     private int customersCustId;
     private int locationsLocId;

    public TillTapeId() {
    }

    public TillTapeId(int TId, int usersUserId, int customersCustId, int locationsLocId) {
       this.TId = TId;
       this.usersUserId = usersUserId;
       this.customersCustId = customersCustId;
       this.locationsLocId = locationsLocId;
    }
   
    public int getTId() {
        return this.TId;
    }
    
    public void setTId(int TId) {
        this.TId = TId;
    }
    public int getUsersUserId() {
        return this.usersUserId;
    }
    
    public void setUsersUserId(int usersUserId) {
        this.usersUserId = usersUserId;
    }
    public int getCustomersCustId() {
        return this.customersCustId;
    }
    
    public void setCustomersCustId(int customersCustId) {
        this.customersCustId = customersCustId;
    }
    public int getLocationsLocId() {
        return this.locationsLocId;
    }
    
    public void setLocationsLocId(int locationsLocId) {
        this.locationsLocId = locationsLocId;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 59 * hash + this.TId;
        hash = 59 * hash + this.usersUserId;
        hash = 59 * hash + this.customersCustId;
        hash = 59 * hash + this.locationsLocId;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TillTapeId other = (TillTapeId) obj;
        if (this.TId != other.TId) {
            return false;
        }
        if (this.usersUserId != other.usersUserId) {
            return false;
        }
        if (this.customersCustId != other.customersCustId) {
            return false;
        }
        if (this.locationsLocId != other.locationsLocId) {
            return false;
        }
        return true;
    }




}


