package entity;
// Generated Aug 1, 2015 5:45:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userId;
     private String name;
     private String password;
     private Byte level;
     private Set tillTapes = new HashSet(0);

    public Users() {
    }

    public Users(String name, String password, Byte level, Set tillTapes) {
       this.name = name;
       this.password = password;
       this.level = level;
       this.tillTapes = tillTapes;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Byte getLevel() {
        return this.level;
    }
    
    public void setLevel(Byte level) {
        this.level = level;
    }
    public Set getTillTapes() {
        return this.tillTapes;
    }
    
    public void setTillTapes(Set tillTapes) {
        this.tillTapes = tillTapes;
    }




}


