package entity;
// Generated Oct 11, 2015 7:56:58 PM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="fire_tickets"
)
public class Users  implements java.io.Serializable {


     private Integer userId;
     private String name;
     private String password;
     private Byte level;
     private Set<TillTape> tillTapes = new HashSet<TillTape>(0);

    public Users() {
    }

    public Users(String name, String password, Byte level, Set<TillTape> tillTapes) {
       this.name = name;
       this.password = password;
       this.level = level;
       this.tillTapes = tillTapes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="name", length=12)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="password", length=12)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="level")
    public Byte getLevel() {
        return this.level;
    }
    
    public void setLevel(Byte level) {
        this.level = level;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<TillTape> getTillTapes() {
        return this.tillTapes;
    }
    
    public void setTillTapes(Set<TillTape> tillTapes) {
        this.tillTapes = tillTapes;
    }



}


