package firetickets2;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MfgId generated by hbm2java
 */
public class MfgId  implements java.io.Serializable {


     private Integer mfgId;
     private String name;
     private String mfgAbr;
     private Set gameTemplateses = new HashSet(0);

    public MfgId() {
    }

    public MfgId(String name, String mfgAbr, Set gameTemplateses) {
       this.name = name;
       this.mfgAbr = mfgAbr;
       this.gameTemplateses = gameTemplateses;
    }
   
    public Integer getMfgId() {
        return this.mfgId;
    }
    
    public void setMfgId(Integer mfgId) {
        this.mfgId = mfgId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMfgAbr() {
        return this.mfgAbr;
    }
    
    public void setMfgAbr(String mfgAbr) {
        this.mfgAbr = mfgAbr;
    }
    public Set getGameTemplateses() {
        return this.gameTemplateses;
    }
    
    public void setGameTemplateses(Set gameTemplateses) {
        this.gameTemplateses = gameTemplateses;
    }




}


