package firetickets2;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PmaHistory generated by hbm2java
 */
public class PmaHistory  implements java.io.Serializable {


     private Long id;
     private String username;
     private String db;
     private String table;
     private Date timevalue;
     private String sqlquery;

    public PmaHistory() {
    }

    public PmaHistory(String username, String db, String table, Date timevalue, String sqlquery) {
       this.username = username;
       this.db = db;
       this.table = table;
       this.timevalue = timevalue;
       this.sqlquery = sqlquery;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getDb() {
        return this.db;
    }
    
    public void setDb(String db) {
        this.db = db;
    }
    public String getTable() {
        return this.table;
    }
    
    public void setTable(String table) {
        this.table = table;
    }
    public Date getTimevalue() {
        return this.timevalue;
    }
    
    public void setTimevalue(Date timevalue) {
        this.timevalue = timevalue;
    }
    public String getSqlquery() {
        return this.sqlquery;
    }
    
    public void setSqlquery(String sqlquery) {
        this.sqlquery = sqlquery;
    }




}


