package firetickets2;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1



/**
 * PmaNavigationhidingId generated by hbm2java
 */
public class PmaNavigationhidingId  implements java.io.Serializable {


     private String username;
     private String itemName;
     private String itemType;
     private String dbName;
     private String tableName;

    public PmaNavigationhidingId() {
    }

    public PmaNavigationhidingId(String username, String itemName, String itemType, String dbName, String tableName) {
       this.username = username;
       this.itemName = itemName;
       this.itemType = itemType;
       this.dbName = dbName;
       this.tableName = tableName;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public String getItemType() {
        return this.itemType;
    }
    
    public void setItemType(String itemType) {
        this.itemType = itemType;
    }
    public String getDbName() {
        return this.dbName;
    }
    
    public void setDbName(String dbName) {
        this.dbName = dbName;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PmaNavigationhidingId) ) return false;
		 PmaNavigationhidingId castOther = ( PmaNavigationhidingId ) other; 
         
		 return ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && ( (this.getItemName()==castOther.getItemName()) || ( this.getItemName()!=null && castOther.getItemName()!=null && this.getItemName().equals(castOther.getItemName()) ) )
 && ( (this.getItemType()==castOther.getItemType()) || ( this.getItemType()!=null && castOther.getItemType()!=null && this.getItemType().equals(castOther.getItemType()) ) )
 && ( (this.getDbName()==castOther.getDbName()) || ( this.getDbName()!=null && castOther.getDbName()!=null && this.getDbName().equals(castOther.getDbName()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + ( getItemName() == null ? 0 : this.getItemName().hashCode() );
         result = 37 * result + ( getItemType() == null ? 0 : this.getItemType().hashCode() );
         result = 37 * result + ( getDbName() == null ? 0 : this.getDbName().hashCode() );
         result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
         return result;
   }   


}


