package firetickets2;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1



/**
 * PmaNavigationhiding generated by hbm2java
 */
public class PmaNavigationhiding  implements java.io.Serializable {


     private PmaNavigationhidingId id;

    public PmaNavigationhiding() {
    }

    public PmaNavigationhiding(PmaNavigationhidingId id) {
       this.id = id;
    }
   
    public PmaNavigationhidingId getId() {
        return this.id;
    }
    
    public void setId(PmaNavigationhidingId id) {
        this.id = id;
    }




}


