package firetickets2;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1



/**
 * PmaRelation generated by hbm2java
 */
public class PmaRelation  implements java.io.Serializable {


     private PmaRelationId id;
     private String foreignDb;
     private String foreignTable;
     private String foreignField;

    public PmaRelation() {
    }

    public PmaRelation(PmaRelationId id, String foreignDb, String foreignTable, String foreignField) {
       this.id = id;
       this.foreignDb = foreignDb;
       this.foreignTable = foreignTable;
       this.foreignField = foreignField;
    }
   
    public PmaRelationId getId() {
        return this.id;
    }
    
    public void setId(PmaRelationId id) {
        this.id = id;
    }
    public String getForeignDb() {
        return this.foreignDb;
    }
    
    public void setForeignDb(String foreignDb) {
        this.foreignDb = foreignDb;
    }
    public String getForeignTable() {
        return this.foreignTable;
    }
    
    public void setForeignTable(String foreignTable) {
        this.foreignTable = foreignTable;
    }
    public String getForeignField() {
        return this.foreignField;
    }
    
    public void setForeignField(String foreignField) {
        this.foreignField = foreignField;
    }




}


