package firetickets2;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1



/**
 * PmaRelationId generated by hbm2java
 */
public class PmaRelationId  implements java.io.Serializable {


     private String masterDb;
     private String masterTable;
     private String masterField;

    public PmaRelationId() {
    }

    public PmaRelationId(String masterDb, String masterTable, String masterField) {
       this.masterDb = masterDb;
       this.masterTable = masterTable;
       this.masterField = masterField;
    }
   
    public String getMasterDb() {
        return this.masterDb;
    }
    
    public void setMasterDb(String masterDb) {
        this.masterDb = masterDb;
    }
    public String getMasterTable() {
        return this.masterTable;
    }
    
    public void setMasterTable(String masterTable) {
        this.masterTable = masterTable;
    }
    public String getMasterField() {
        return this.masterField;
    }
    
    public void setMasterField(String masterField) {
        this.masterField = masterField;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PmaRelationId) ) return false;
		 PmaRelationId castOther = ( PmaRelationId ) other; 
         
		 return ( (this.getMasterDb()==castOther.getMasterDb()) || ( this.getMasterDb()!=null && castOther.getMasterDb()!=null && this.getMasterDb().equals(castOther.getMasterDb()) ) )
 && ( (this.getMasterTable()==castOther.getMasterTable()) || ( this.getMasterTable()!=null && castOther.getMasterTable()!=null && this.getMasterTable().equals(castOther.getMasterTable()) ) )
 && ( (this.getMasterField()==castOther.getMasterField()) || ( this.getMasterField()!=null && castOther.getMasterField()!=null && this.getMasterField().equals(castOther.getMasterField()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMasterDb() == null ? 0 : this.getMasterDb().hashCode() );
         result = 37 * result + ( getMasterTable() == null ? 0 : this.getMasterTable().hashCode() );
         result = 37 * result + ( getMasterField() == null ? 0 : this.getMasterField().hashCode() );
         return result;
   }   


}


