package firetickets2;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1



/**
 * PmaTableCoordsId generated by hbm2java
 */
public class PmaTableCoordsId  implements java.io.Serializable {


     private String dbName;
     private String tableName;
     private int pdfPageNumber;

    public PmaTableCoordsId() {
    }

    public PmaTableCoordsId(String dbName, String tableName, int pdfPageNumber) {
       this.dbName = dbName;
       this.tableName = tableName;
       this.pdfPageNumber = pdfPageNumber;
    }
   
    public String getDbName() {
        return this.dbName;
    }
    
    public void setDbName(String dbName) {
        this.dbName = dbName;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public int getPdfPageNumber() {
        return this.pdfPageNumber;
    }
    
    public void setPdfPageNumber(int pdfPageNumber) {
        this.pdfPageNumber = pdfPageNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PmaTableCoordsId) ) return false;
		 PmaTableCoordsId castOther = ( PmaTableCoordsId ) other; 
         
		 return ( (this.getDbName()==castOther.getDbName()) || ( this.getDbName()!=null && castOther.getDbName()!=null && this.getDbName().equals(castOther.getDbName()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && (this.getPdfPageNumber()==castOther.getPdfPageNumber());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDbName() == null ? 0 : this.getDbName().hashCode() );
         result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
         result = 37 * result + this.getPdfPageNumber();
         return result;
   }   


}


