package firetickets2;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1



/**
 * PmaTableInfoId generated by hbm2java
 */
public class PmaTableInfoId  implements java.io.Serializable {


     private String dbName;
     private String tableName;

    public PmaTableInfoId() {
    }

    public PmaTableInfoId(String dbName, String tableName) {
       this.dbName = dbName;
       this.tableName = tableName;
    }
   
    public String getDbName() {
        return this.dbName;
    }
    
    public void setDbName(String dbName) {
        this.dbName = dbName;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PmaTableInfoId) ) return false;
		 PmaTableInfoId castOther = ( PmaTableInfoId ) other; 
         
		 return ( (this.getDbName()==castOther.getDbName()) || ( this.getDbName()!=null && castOther.getDbName()!=null && this.getDbName().equals(castOther.getDbName()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDbName() == null ? 0 : this.getDbName().hashCode() );
         result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
         return result;
   }   


}


