package firetickets2;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PmaTracking generated by hbm2java
 */
public class PmaTracking  implements java.io.Serializable {


     private PmaTrackingId id;
     private Date dateCreated;
     private Date dateUpdated;
     private String schemaSnapshot;
     private String schemaSql;
     private String dataSql;
     private String tracking;
     private int trackingActive;

    public PmaTracking() {
    }

	
    public PmaTracking(PmaTrackingId id, Date dateCreated, Date dateUpdated, String schemaSnapshot, int trackingActive) {
        this.id = id;
        this.dateCreated = dateCreated;
        this.dateUpdated = dateUpdated;
        this.schemaSnapshot = schemaSnapshot;
        this.trackingActive = trackingActive;
    }
    public PmaTracking(PmaTrackingId id, Date dateCreated, Date dateUpdated, String schemaSnapshot, String schemaSql, String dataSql, String tracking, int trackingActive) {
       this.id = id;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
       this.schemaSnapshot = schemaSnapshot;
       this.schemaSql = schemaSql;
       this.dataSql = dataSql;
       this.tracking = tracking;
       this.trackingActive = trackingActive;
    }
   
    public PmaTrackingId getId() {
        return this.id;
    }
    
    public void setId(PmaTrackingId id) {
        this.id = id;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }
    public String getSchemaSnapshot() {
        return this.schemaSnapshot;
    }
    
    public void setSchemaSnapshot(String schemaSnapshot) {
        this.schemaSnapshot = schemaSnapshot;
    }
    public String getSchemaSql() {
        return this.schemaSql;
    }
    
    public void setSchemaSql(String schemaSql) {
        this.schemaSql = schemaSql;
    }
    public String getDataSql() {
        return this.dataSql;
    }
    
    public void setDataSql(String dataSql) {
        this.dataSql = dataSql;
    }
    public String getTracking() {
        return this.tracking;
    }
    
    public void setTracking(String tracking) {
        this.tracking = tracking;
    }
    public int getTrackingActive() {
        return this.trackingActive;
    }
    
    public void setTrackingActive(int trackingActive) {
        this.trackingActive = trackingActive;
    }




}


