package firetickets2;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1



/**
 * PmaTableInfo generated by hbm2java
 */
public class PmaTableInfo  implements java.io.Serializable {


     private PmaTableInfoId id;
     private String displayField;

    public PmaTableInfo() {
    }

    public PmaTableInfo(PmaTableInfoId id, String displayField) {
       this.id = id;
       this.displayField = displayField;
    }
   
    public PmaTableInfoId getId() {
        return this.id;
    }
    
    public void setId(PmaTableInfoId id) {
        this.id = id;
    }
    public String getDisplayField() {
        return this.displayField;
    }
    
    public void setDisplayField(String displayField) {
        this.displayField = displayField;
    }




}


