package firetickets2;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1



/**
 * PmaUsergroupsId generated by hbm2java
 */
public class PmaUsergroupsId  implements java.io.Serializable {


     private String usergroup;
     private String tab;
     private String allowed;

    public PmaUsergroupsId() {
    }

    public PmaUsergroupsId(String usergroup, String tab, String allowed) {
       this.usergroup = usergroup;
       this.tab = tab;
       this.allowed = allowed;
    }
   
    public String getUsergroup() {
        return this.usergroup;
    }
    
    public void setUsergroup(String usergroup) {
        this.usergroup = usergroup;
    }
    public String getTab() {
        return this.tab;
    }
    
    public void setTab(String tab) {
        this.tab = tab;
    }
    public String getAllowed() {
        return this.allowed;
    }
    
    public void setAllowed(String allowed) {
        this.allowed = allowed;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PmaUsergroupsId) ) return false;
		 PmaUsergroupsId castOther = ( PmaUsergroupsId ) other; 
         
		 return ( (this.getUsergroup()==castOther.getUsergroup()) || ( this.getUsergroup()!=null && castOther.getUsergroup()!=null && this.getUsergroup().equals(castOther.getUsergroup()) ) )
 && ( (this.getTab()==castOther.getTab()) || ( this.getTab()!=null && castOther.getTab()!=null && this.getTab().equals(castOther.getTab()) ) )
 && ( (this.getAllowed()==castOther.getAllowed()) || ( this.getAllowed()!=null && castOther.getAllowed()!=null && this.getAllowed().equals(castOther.getAllowed()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsergroup() == null ? 0 : this.getUsergroup().hashCode() );
         result = 37 * result + ( getTab() == null ? 0 : this.getTab().hashCode() );
         result = 37 * result + ( getAllowed() == null ? 0 : this.getAllowed().hashCode() );
         return result;
   }   


}


