package firetickets2;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1



/**
 * PmaUsergroups generated by hbm2java
 */
public class PmaUsergroups  implements java.io.Serializable {


     private PmaUsergroupsId id;

    public PmaUsergroups() {
    }

    public PmaUsergroups(PmaUsergroupsId id) {
       this.id = id;
    }
   
    public PmaUsergroupsId getId() {
        return this.id;
    }
    
    public void setId(PmaUsergroupsId id) {
        this.id = id;
    }




}


