package firetickets2;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1



/**
 * PmaUsers generated by hbm2java
 */
public class PmaUsers  implements java.io.Serializable {


     private PmaUsersId id;

    public PmaUsers() {
    }

    public PmaUsers(PmaUsersId id) {
       this.id = id;
    }
   
    public PmaUsersId getId() {
        return this.id;
    }
    
    public void setId(PmaUsersId id) {
        this.id = id;
    }




}


