package firetickets2;
// Generated Sep 8, 2015 7:01:42 PM by Hibernate Tools 4.3.1



/**
 * PmaUsersId generated by hbm2java
 */
public class PmaUsersId  implements java.io.Serializable {


     private String username;
     private String usergroup;

    public PmaUsersId() {
    }

    public PmaUsersId(String username, String usergroup) {
       this.username = username;
       this.usergroup = usergroup;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getUsergroup() {
        return this.usergroup;
    }
    
    public void setUsergroup(String usergroup) {
        this.usergroup = usergroup;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PmaUsersId) ) return false;
		 PmaUsersId castOther = ( PmaUsersId ) other; 
         
		 return ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && ( (this.getUsergroup()==castOther.getUsergroup()) || ( this.getUsergroup()!=null && castOther.getUsergroup()!=null && this.getUsergroup().equals(castOther.getUsergroup()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + ( getUsergroup() == null ? 0 : this.getUsergroup().hashCode() );
         return result;
   }   


}


